### ISSUE TITLE
Getting upload file arrayBuffer server side in validation function fails with "Attempted to call a temporary Client Reference"

### ISSUE THREAD

**Issue by sacha-c** [payloadcms/payload#10038]
### Describe the Bug

I have an upload collection that I validate with a sibling checkbox field. The checkbox field has a validation method which checks the `options.siblingData.file` when it is populated and runs some file validations with the underlying File object.

This used to work in V2, but in V3 when trying to migrate my logic I end up with the error `Error: Attempted to call a temporary Client Reference from the server but it is on the client.`

(Maybe I am abusing an API that is not supposed to be public, if so please suggest an alternative that would allow me to validate a file server-side, loading the Blob in memory. I also explored `hooks.beforeOperation` but could not give nice validation feedback in the UI to the user using it)

### Link to the code that reproduces this issue

https://github.com/sacha-c/payload/commit/b119e4e32de790e09feb59d70e4ea12deddeee7b

### Reproduction Steps

Have a collection with an upload configuration & a sibling field with a validation method that attempts to access the `arrayBuffer` promise (or the `stream()` or `text()` methods also)

```ts
  upload: {
     // My upload config
     ...
  }
  fields: [
    {
      name: 'test',
      type: 'checkbox',
      validate: async (_, options): Promise<string | true> => {
        if (!('file' in options.siblingData)) {
          // Payload has not loaded the file yet, pass validation
          return true
        }

        try {
          const result = await (options.siblingData.file as File).arrayBuffer()
          console.log('result', result)

          // perform validation with the arrayBuffer, loading it in memory & checking details of the object
          // ...
        } catch (error) {
          console.log('error', error)
        }

        return true
      },
    },
  ],
```

Logs:
```
error Error: Attempted to call a temporary Client Reference from the server but it is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
...
```

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
Payload: 3.8.0 
Node.js: 22.6.0
Next.js: 15.0.3
```

**Comment by jmikrut** [comment]
Hey @sacha-c — this is because in 2.0, the `validate` function ran on both the server and the client - but in 3.0, it's run only on the server.

The `file` in the `siblingData` is going to be the browser-based file, which is why you are seeing the error that you're seeing.

File objects are browser-specific and represent file uploads from the client-side. They exist in the client's JS runtime.

When you call `await (options.siblingData.file as File).arrayBuffer()` on the server, it doesn't have the necessary context (or APIs) to execute this method because it doesn't have access to the browser's File interface.

Another consideration is that the `validate` functions are executed a _**lot**_ - on every change to the form state. They should be as fast and as minimal as possible.

This all leads me to suggest that if you want to validate a file, you should instead validate it in a `beforeValidate` hook and look at `req.file`. This way it will only be validated once, when you go to save, and you can then manipulate the arrayBuffer however you want.

Does this make sense?
