### ISSUE TITLE
Version draft false clarification

### ISSUE THREAD

**Issue by snakemastr** [payloadcms/payload#10067]
# Documentation Issue

Related issue: https://github.com/payloadcms/payload/issues/8077
When enabling versions with drafts and using the draft:false argument in find/findById operations, it's expected to only return published documents. 
Yet the operation returns the latest published document OR the latest unpublished document if no published documents exist.

The solution provided in the github issue is to add a where clause to check for status field equals published.

This negates the effect of drafts imo, and I fail to see it's use-case in a production environment. (I either want only published documents or only latest version regardless of status)

Can this be added to the docs, for example in https://payloadcms.com/docs/versions/drafts#reading-drafts-vs-published-documents?

**Comment by ivkrpv** [comment]
agree, also found this a bit confusing

**Comment by jmikrut** [comment]
Hey all,

I just added a warning message to the docs in that section.

https://github.com/payloadcms/payload/commit/fe010b9373230811d6dbcd11cab4f4b45a7c0955

This is very much so by design, and I agree that it is confusing, but the problem I think is the _**naming**_ of the `draft` argument. It really should be named something like `returnNewestVersion` or similar - because that's all it does. It has nothing to do with access control. 

We will likely rename this property in v4. Thanks for bringing this up though!
