### ISSUE TITLE
fetch failed error in creating payload app with create-payload-app

### ISSUE THREAD

**Issue by Inna-Mykytiuk** [payloadcms/payload#10151]
### Describe the Bug

Every time I want to install an app, I get this message, no matter if I use npx or pnpx

$ npx create-payload-app

┌ create-payload-app
│
◇ ────────────────────────────────────────────╮
│ │
│ Welcome to Payload. Let's create a project! │
│ │
├───────────────────────────────────────────────╯
│
◇ Project name?
│ payload
│
◇ Choose project template
│ blank
│
◇ Select a database
│ MongoDB
│
◇ Enter MongoDB connection string
│ mongodb://127.0.0.1/payload
│
■ fetch failed

or

$ npx create-payload-app

┌ create-payload-app
│
◇ ────────────────────────────────────────────╮
│ │
│ Welcome to Payload. Let's create a project! │
│ │
├───────────────────────────────────────────────╯
│
◇ Project name?
│ payload-test
│
◇ Choose project template
│ blank
│
◇ Select a database
│ MongoDB
│
◇ Enter MongoDB connection string
│ mongodb+srv://innkapinnka:[Ofvsdfsdf3W....s@cluster3.r5xst.mongodb.net](mailto:Ofvsdfsdf3W....s@cluster3.r5xst.mongodb.net)/
│
■ fetch failed

Result will be the same. Help me please.![Image](https://github.com/user-attachments/assets/e588daf7-de4e-4c86-be35-b346a52990f1)
![Image](https://github.com/user-attachments/assets/dc315924-1319-4fe8-a7ba-59614bf4c863)
![Image](https://github.com/user-attachments/assets/685c8795-7e00-4223-9359-8656fc481c8f)

### Link to the code that reproduces this issue

---

### Reproduction Steps

create payload application with following steps
1 pnpx create-payload-app
2. Select a database as MongoDB
3. Enter MongoDB connection string
it will breakdown with fetch failed error

### Which area(s) are affected? (Select all that apply)

area: core

### Environment Info

```text
create-payload-app@
```

**Comment by Inna-Mykytiuk** [comment]
this issue marked with the invalid-reproduction label because I can't create new repository. I can copy your template, but I want to understand why I can't create app from scratch with terminal

**Comment by denolfe** [comment]
Hey @Inna-Mykytiuk , this error is likely due to not being able to fetch the template code from the github URL. You can get more info by passing the `--debug` flag to the CLI. 

It will give back a URL like `https://codeload.github.com/payloadcms/payload/tar.gz/main`. 

Can you verify that you're able to reach that file in a browser? It will attempt to download the specified file.

**Comment by Inna-Mykytiuk** [comment]
No access, The connection is not confidential and is marked as potentially threatening to my system.

**Comment by elghaied** [comment]
hello @Inna-Mykytiuk , do you have the same issue if you try to install next js 
`npx create-next-app@latest`

**Comment by Inna-Mykytiuk** [comment]
No, I don't have problem with Next installation

**Comment by Inna-Mykytiuk** [comment]
This problem with payload occurs both on the computer and on the laptop, the Windows10-11 operating system

**Comment by elghaied** [comment]
@Inna-Mykytiuk  I searched a bit, most cases were because of VPN/Proxy or antivirus and firewalls 

when you run this what you get 

`node -e "require('https').get('https://raw.githubusercontent.com/payloadcms/payload/refs/heads/main/templates/website/package.json', res => { res.setEncoding('utf8'); res.on('data', console.log); res.on('error', console.error); }).on('error', console.error);"

`

**Comment by denolfe** [comment]
This appears to be very specific to your networking setup. Beyond fixing that configuration, it may be easier to grab the code directly from the repository [here](https://github.com/payloadcms/payload/tree/main/templates/blank) by either cloning the repository and copying or downloading the repo via zip and copying.

Closing this as it is something to do w/ your specific setup and no others are seeing this issue.
