### ISSUE TITLE
Bug: Uploading image in hasMany field populates unrelated upload field

### ISSUE THREAD

**Issue by adesombergh** [payloadcms/payload#10177]
### Describe the Bug

When using PayloadCMS with a collection or global that includes:
1. An upload field with hasMany enabled.
2. Another upload field placed after it.

If you use the “Create New” option in the first upload field (hasMany), the uploaded image unexpectedly populates the second upload field and leaves the first one empty.

### Link to the code that reproduces this issue

https://github.com/adesombergh/payload

### Reproduction Steps

1.	Create a collection or global with:
• An upload field with hasMany enabled.
• A second upload field immediately following it.
2.	Go to the admin panel and create a new document in the collection (or edit the global).
3.	For the hasMany upload field:
•	Select “Create New” and upload an image.
4.	Observe that the second upload field is unexpectedly populated with the uploaded image, while the first one stays empty.

### Which area(s) are affected? (Select all that apply)

core, ui

### Environment Info

```text
Payload: 3.11.0
Next: 15.0.3
Node: 20.18.1
```

**Comment by akhrarovsaid** [comment]
Yeah, I've reproduced this. I _think_ this is happening because the `UploadField` component sets an `onSuccess` callback for the bulk drawer component, however only a `hasMany` upload field actually makes use of it. By setting it for non-`hasMany` fields, you get this bug here. I'll have a PR out for this right after I test a few more scenarios.
