### ISSUE TITLE
importance of serverURL not mentioned

### ISSUE THREAD

**Issue by GuyRubi** [payloadcms/payload#10235]
# Documentation Issue

The documentation does not specify that functions such as payload.forgotPassword are dependent on `serverURL` being set (and will silently fail if its `null`!) 

As a side note, I wonder why the default value isn't `setServerSideURL()` rather than `null`.

**Comment by jmikrut** [comment]
Hey @GuyRubi — are you talking about the website template? Where do you see the `serverURL` set as `null`?

The `forgotPassword` and `verify` emails should function appropriately via REST / GraphQL operations because there, if you do not have a `serverURL` set, we will automatically try and create one for you using this approach:

```ts
      const protocol = new URL(req.url).protocol
      const serverURL =
        config.serverURL !== null && config.serverURL !== ''
          ? config.serverURL
          : `${protocol}//${req.headers.get('host')}`
``` 

But I will update the docs regardless with a bit of clarity here.

**Comment by GuyRubi** [comment]
I wasn't passing in a req so I guess thats on me, still I think its helpful to be aware of this behavior. thank you for the fix
