### ISSUE TITLE
Required relationships showing as Nullable type in GraphQL Schema

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#1148]
# Bug Report

[From Discord](https://discord.com/channels/967097582721572934/967104816893530222/1021802589756600322)

> hey guys, regarding generated GraphQL types, i'm noticing that in some cases, when i have specified that a field is required, i still get a nullable type generated in the GraphQL schema. specifically i'm finding this always happens with relation fields. is this expected?

> what i'm noticing is that it happens to any relation. if you've got a Payload instance handy with a relationship instance, you should see the nullable type in the graphQL schema

## Expected Behavior

Required relationship shows as non-nullable

## Detailed Description

Payload 1.0.31

**Comment by pugbyte** [comment]
I believe this expected behaviour is that a required field should show up an _non-nullable_ in the GraphQL schema.

**Comment by denolfe** [comment]
@pugbyte Correct, I was flying through it. Edited 👍

**Comment by jmikrut** [comment]
I actually think that this is intended behavior. If a field has any of the following conditions, it will NEED to be `nullable` in GraphQL, because it can potentially be missing:

- If the field has a condition
- If the field is localized
- If the field has `read` access control that might prevent it from being populated

If the field has none of these things, and it is set to `required`, then the field will be correctly specified as non-nullable in GraphQL.

Does that make sense?
