### ISSUE TITLE
Weird bug that scroll to load more feature not working on Win10/iOS13 Chrome

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#1360]
# Bug Report

## Current Behavior

No 2nd page is loaded when scrolling in the relationship dropdown. The editor need to type in the whole name (which is hard to type or remember without auto-complete)  to find the desired relationship.

## Expected Behavior

Expect loading more relationships when scrolling down to the bottom.

## Steps to Reproduce

We cannot reproduce this bug except on the computer of one of our editors, but I can reproduce it with my iPhone + Chrome

Here is a video of how to reproduce it in iPhone.

https://user-images.githubusercontent.com/5801015/200977945-cb3c9693-fa74-446c-b810-43faff3d289a.mp4

Here's the loom video from the editor: https://www.loom.com/share/42e472f896bf4b0c9d4887278224bb0b

## Detailed Description

OS: Win10 or iOS 13
Browser: Chrome

**Comment by thgh** [comment]
Probably because jmikrut closed this as [completed](https://github.com/payloadcms/payload/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) in https://github.com/payloadcms/payload/commit/7136db4c718b70833fa75f5c8e9ae596298b3aa9 [2 days ago](https://github.com/payloadcms/payload/issues/1360#event-7797256143)
Do you encounter the same bug in v1.1.24?
