### ISSUE TITLE
Generate types should use the slug as interface name

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#1371]
# Bug Report

I'm using `labels.singular` as a Dutch label to show in the UI, but I only want English code. So when generating typescript interfaces from collections, it's quite unexpected to have them in Dutch. 

Example:

```ts
export const Page: CollectionConfig = {
  slug: 'pages',
  labels: { singular: 'Pagina', plural: "Pagina's" },
```

## Current Behavior

```ts
// Output
interface Pagina {
```

## Expected Behavior

```ts
// Output
interface Page {
```

### Possible Solution 1

Derive the interface from the collection slug and [singularize](https://www.npmjs.com/package/pluralize) it.
```ts
export const Pages: CollectionConfig = {
  slug: 'pages',
```

It would then make sense to follow the pattern of naming the collection config object in plural: `Pages` and the type singular `Page` to avoid naming collisions.

### Possible Solution 2

Extra field
```ts
export const Pages: CollectionConfig = {
  slug: 'pages',
  generatedType: 'Page',
  labels: { singular: 'Pagina', plural: "Pagina's" },
```

### Possible Solution 3

Extra field but more future proof
```ts
export const Pages: CollectionConfig = {
  slug: 'pages',
  typescript: { interface: 'Page' },
  labels: { singular: 'Pagina', plural: "Pagina's" },
```

### Possible Solution 4

Use a workaround like this:
```ts
export const Pages: CollectionConfig = {
  slug: 'pages',
  labels:
    typeof window === 'undefined'
      ? { singular: 'Page' }
      : { singular: 'Pagina', plural: "Pagina's" },
```

## Steps to Reproduce

1. `payload generate:types`

**Comment by DanRibbens** [comment]
I've been working on this exact problem this week but for GraphQL. It is going to coming with the changes here: https://github.com/payloadcms/payload/pull/1326

I'd like to just use the slug and singularize it. For GraphQL we decided to do add a config property for the GraphQL names of collections and globals. We are doing this to give devs a way to set it so as not to break already existing sites and codebases reliant on the labels. Since Typescript generation is optional and doesn't impact the APIs I don't feel like we need to add a way to configure it.

I'll talk with the team, we may do this in the same release as the GraphQL change.

**Comment by DanRibbens** [comment]
I went ahead and added this to my changes going into the i18n PR. 

[`1ecf2a9` (#1326)](https://github.com/payloadcms/payload/pull/1326/commits/1ecf2a9a06fa334dd9af31600bdefa73d9c0410b)
