### ISSUE TITLE
Delete button stays visible when access is query based

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#1375]
# Bug Report

When using a function like this:

```ts
access: {
  delete: () => ({ confirmed: { equals: false } }),
}
```

## Current Behavior

The delete button stays visible and triggers an error when clicked.

## Expected Behavior

The delete button is hidden when the document is undeletable.

## Possible Solution

A clientside mongo query evaluator would be able to handle this. If there was support for `in` and `equals`, that would already go a long way.

## Steps to Reproduce

1. Set `delete` access that returns a boolean
2. It works as expected
3. Set `delete` access that returns a query
4. It doesn't work as expected

## Detailed Description

Same for `create`

**Comment by jmikrut** [comment]
Hey @thgh this is related to this discussion:

https://github.com/payloadcms/payload/discussions/1379

We have a `planned` roadmap item open to address this. But right now, this is expected behavior. We're going to address this ASAP, but in the interim, I'm going to close this issue and defer conversation to take place on the discussion above.

**Comment by JarrodMFlesch** [comment]
@thgh, 1.3.2 just released, and this functionality is now available. Document level access now runs when a doc is loaded and after it is saved! Give this a shot, I think you have a great use case for this feature.
