### ISSUE TITLE
Failed to install dependencies

### ISSUE THREAD

**Issue by lodisy** [payloadcms/payload#1412]
# Bug Report

No matching version found for @faceless-ui/modal@^2.0.1

## Current Behavior

No matching version found for @faceless-ui/modal@^2.0.1

## Expected Behavior

Able to install the 2.0.1 version, https://www.npmjs.com/package/@faceless-ui/modal

## Steps to Reproduce

1. Run `npx create-payload-app` on M1 Mac
2. Failed to install dependencies
3. `cd` directory, run, manually install 
4. Still failed
5. Tried switching the npmjs registery, not worked

**Comment by jmikrut** [comment]
Hey @lodisy — I am not able to reproduce. I just installed a new copy of Payload via `npx create-payload-app` on an M1 Mac and it worked right out of the box. It's probably something with your setup. But if the issue persists, and you can't find a solution, you should open this up on the @faceless-ui/modal package instead of here!
