### ISSUE TITLE
Array minRows sometimes return number 1 instead of object in data

### ISSUE THREAD

**Issue by wloodar** [payloadcms/payload#1502]
# Bug Report

When I add minRows, in this situation minRows = 1 to my array field, I randomly get validation error. I console log the data object in beforeChange hook and when this error occurs, value from that field is returned with value 1. When operation is successful, returned value is regular object with data from that array field.

<img width="484" alt="Screenshot 2022-11-24 at 10 57 24" src="https://user-images.githubusercontent.com/56487194/203754220-584d951b-62b1-4fa6-a4bd-bd91a4bed367.png">

The last one in this screenshot causes the error.

<img width="313" alt="Screenshot 2022-11-24 at 10 58 20" src="https://user-images.githubusercontent.com/56487194/203754409-ad406f51-afd9-4901-a657-cd0e4cbaa0ac.png">

Field definition

## Steps to Reproduce

1. Create array field
2. Add minRows = 1
3. Try to add multiple entries to collection

## Other Details

Payload version 1.1.19

**Comment by jacobsfletch** [comment]
Hey @wloodar I am not able to recreate this, but I went ahead and took a screen-recording so you could see what I've got going on:

https://user-images.githubusercontent.com/15735305/204378446-80a9f597-13cf-4f0a-9d11-f65690209c9e.mp4

I do see you are firing a request out to revalidate your front-end, probably in an `afterChange` hook. Try temporarily removing that and see if your bug continues. Otherwise, can you send me your full config so I can try and replicate your setup _exactly_?
