### ISSUE TITLE
Media collection doesn't work when api route is empty

### ISSUE THREAD

**Issue by 383bd03d** [payloadcms/payload#1623]
All media files in collection with upload return Not found
payload v. 1.2.5

`payload-cms:dev: [12:23:23] ERROR (payload): NotFound: Запрашиваемый ресурс не найден.
payload-cms:dev:     at new ExtendableError (/Users/user/Developer/project/node_modules/payload/src/errors/APIError.ts:26:11)
payload-cms:dev:     at new APIError (/Users/user/Developer/project/node_modules/payload/src/errors/APIError.ts:43:5)
payload-cms:dev:     at new NotFound (/Users/user/Developer/project/node_modules/payload/src/errors/NotFound.ts:7:5)
payload-cms:dev:     at findByID (/Users/user/Developer/project/node_modules/payload/src/collections/operations/findByID.ts:112:13)
payload-cms:dev:     at runMicrotasks (<anonymous>)
payload-cms:dev:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
payload-cms:dev:     at findByIDHandler (/Users/user/Developer/project/node_modules/payload/src/collections/requestHandlers/findByID.ts:13:17)`

**Comment by JarrodMFlesch** [comment]
@383bd03d could you describe what you are attempting to do a bit more? If you could share a config file that would be awesome as well.

I just tested upload collections and upload fields, both worked as expected on my end. Let me know if you have more information! 👍

**Comment by 383bd03d** [comment]
I got this error on existing uploads, when I switch to empty api route

**Comment by DanRibbens** [comment]
I was able to reproduce the problem with the following:

1. In my config: `routes: { api: ''}`
2. Have a collection with `upload` set up with staticURL and staticDir.
3. In the admin UI upload a file.

See that the URL being hit is being picked up by the api instead of being served statically.

I don't see a way to solve this though.
If we rearrange the route bindings it breaks the api. Here is what is now, swapping the two is bad.
```ts
// /src/init.ts
    // Bind router to API
    payload.express.use(payload.config.routes.api, payload.router);

    // Enable static routes for all collections permitting upload
    initStatic(payload);
```

So your media requests are always going to compete with the /api route. Somehow you need to figure out how to let the static routes go through instead of being handled by the API and failing.

If we can't figure it out then I think we should just revert the earlier change that allows `api: ''` as it isn't well supported.

**Comment by JarrodMFlesch** [comment]
I believe this is related to [this feature discussion](https://github.com/payloadcms/payload/discussions/1571) as well.

**Comment by DanRibbens** [comment]
I reverted the changes that allowed this to happen.

For now I say we shouldn't support api routes of `''` until we handle the discussion Jarrod linked (https://github.com/payloadcms/payload/discussions/1571)
