### ISSUE TITLE
Select field cannot clear value

### ISSUE THREAD

**Issue by cmngan** [payloadcms/payload#1655]
# Bug Report

Select field: Once selected a value and saved, cannot clear it. 

## Steps to Reproduce

1. have a select field, e.g. 
```
    {
      name: "foo",
      type: "select",
      options: [
        { label: "Theatre", value: "theatre" },
        { label: "Classroom", value: "classroom" },
      ],
      hooks: {
        beforeChange: [
          ({ value }) => {
            // just for testing. It is null after click `x` button. But after saved, the old value comes
            console.log("value", value);
            return value;
          },
        ],
      },
    },
```
2. Select a value, e.g. `classroom`. Saved
3. Clear the value, by the `x` button in selection box. saved
4. The old value, `classroom`, appeared again.

## Other Details
Payload: v1.3.0

**Comment by JarrodMFlesch** [comment]
Ok, so in your hook the value should be `null`, when it hits our internal beforeChange hook we adjust the value and set it to undefined. The issue likely lives within this small section [here](https://github.com/payloadcms/payload/blob/master/src/fields/hooks/beforeChange/promise.ts#L157)

We can take a closer look at this 👀

**Comment by cmngan** [comment]
The hooks and beforeChange are irrelevant in the example. If it is removed, the behaviour is the same, i.e. cannot clear/reset value in select.

**Comment by JarrodMFlesch** [comment]
@cmngan yep, I understand what you are saying, I was just providing context really.

**Comment by DanRibbens** [comment]
@PatrikKozak isolated the issue here and it is because our update API reassigns `null` to `undefined` which then is ignored when the update is made to the database. We talked about some different options for handling the problem:

1. Allow `null` in the enum for `select` fields when building schema anytime.
2. Allow `null` in the enum for `select` fields when building schema only when `admin.isClearable` is used.
3. Use mongoose's [$unset](https://www.mongodb.com/docs/manual/reference/operator/aggregation/unset/#remove-embedded-fields) aggregation to actually reassign removed field values from documents. This would be useful in more than just `select`, but the effort in calling this and tracking nested paths is way beyond the scope of fixing this bug.
