### ISSUE TITLE
Exists filter doesn't work as expected on relations

### ISSUE THREAD

**Issue by lucaslcode** [payloadcms/payload#1786]
# Bug Report

Exists query filter doesn't seem to work with relation fields.

## Steps to Reproduce

1. Create a collection with a relation field
2. Populate with some example data, some rows having a relation and some leaving it blank
3. Use the exists filter in the admin panel or api

## Other Details

Payload 1.2.1
Can be worked around using `{ equals: null }` instead.

**Comment by jmikrut** [comment]
Hey @lucaslcode — good catch! This was because Mongoose was setting a default value of `[]` for relationship fields that had `hasMany: true`.

This is why `exists` was not working properly on some relationship fields, because tecnhically those fields _**did**_ have an empty array. 

I've just disabled that Mongoose function so newly created docs without values for relationship `hasMany: true` fields will no longer be defaulted to an empty array, but note that this will only affect documents going forward, and you'll need to manually clean up any documents that you've created prior in order for the `exists` operator to function as you expect.

Thanks for the report! This will be released shortly.

**Comment by lucaslcode** [comment]
Thanks so much for your responsiveness! Loving Payload so far :)
