### ISSUE TITLE
Generate types cannot handle a blocks field with empty blocks array

### ISSUE THREAD

**Issue by adiba** [payloadcms/payload#1813]
# Bug Report

When using a field like this
```js
{
  type: 'blocks',
  name: 'blocks',
  blocks: [],
},
```
I get this error upon running `payload generate:types`:
```
SyntaxError: '=>' expected. (69:11)
  67 | id?: string
  68 | }[]
> 69 | blocks: ()[]
     |           ^
  70 | }
  71 | /**
  72 |  * This interface was referenced by `Config`'s 
JSON-Schema
```

## Solution
To generate the blocks property type, use `never` as base. E.g., `(never | {blockType: ...} | {...})[]`

**Comment by jmikrut** [comment]
Hey @adiba — a `blocks` field actually should not be valid unless it has blocks within it. So we're instead going to add validation to prevent having a blocks field from having an empty array of blocks, so that you'll never even hit that TS issue.

Can I ask what you were trying to do with a blocks field with no blocks?

**Comment by adiba** [comment]
@jmikrut Thank you for your reply!
It's very likely that I would want to test a schema/config during development, which might be incomplete.
The same reason applies to anything (e.g., globals) having no fields, which is currently a valid option as well.
(One other reason in my view would be mathematical consistency..)
I don't really mind your choice though -- feel free to add the validation and I'll comment out my blocks field :)
