### ISSUE TITLE
Labels get escaped inconsistently across Dashboard

### ISSUE THREAD

**Issue by sfueg** [payloadcms/payload#1844]
# Bug Report
When defining a label with "special" characters (e.g. `/`) the label will be escaped inconsistently across the Dashboard (see images). I feel like they shouldn't be escaped at all, since they are defined within code but I would at least expect it to be consistent.

## Steps to Reproduce

1. Define a label with a "special" character (e.g. `Example/Plural`)
2. It will be escaped in some places (`Example/Plural` => `Example&#x2F;Plural`)
    but not in others (`Example/Plural` => `Example/Plural`)

### Collection Example:
```ts
const Examples: CollectionConfig = {
  slug: "examples",
  labels: {
    singular: "Example/Singular",
    plural: "Example/Plural",
  },
  ...
};
```
![payload_collection_escapebug](https://user-images.githubusercontent.com/62659085/211555968-e00d585b-22f9-4457-b5c8-42e2f6d158bd.png)

### Global Example:
```ts
const Home: GlobalConfig = {
  slug: "home",
  label: "Page/Home",
  ...
};
```
![payload_global_escapebug](https://user-images.githubusercontent.com/62659085/211555980-05a1ac51-0a80-4786-865e-352755ef5105.png)

## Other Details
Payload version 1.5.4

I had a quick look into the code and I am pretty sure that this behaviour is due to i18next, which escapes values by default.
https://www.i18next.com/translation-function/interpolation#unescape

**Comment by iamprompt** [comment]
I have face the problem too, however I found the solution to add as in the https://www.i18next.com/translation-function/interpolation#additional-options
```
i18n: {
    interpolation: {
      escapeValue: false,
    },
  },
```
to the `payload-config.ts` file, then it will solve the problem.

Question: Should this be added to the default options of the config in https://github.com/payloadcms/payload/blob/master/src/translations/defaultOptions.ts, since the purpose of escaping the special character of i18next is to avoid XSS injection for a security reason. If so, I can open PR to fix that.

**Comment by jacobsfletch** [comment]
> since the purpose of escaping the special character of i18next is to avoid XSS injection for a security reason.

@iamprompt this was exactly my first thought, but React escapes all JSX already (described [here](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks) so this is not an issue.
