### ISSUE TITLE
Debugger breakpoint issue with payload version 1.5.9

### ISSUE THREAD

**Issue by DanieleDeLuis** [payloadcms/payload#1885]
**Description:**

I am using VSCode to debug my code and have encountered an issue with breakpoints. When I set a breakpoint on a specific line and run the debugger with payload version 1.5.9, the execution stops on a different line. This is causing confusion and making it difficult to debug my code. This issue did not occur when using payload version 1.4.0.

**Steps to reproduce:**

1. Open the project in VSCode
2. Set a breakpoint on line X
3. Start the debugger using payload version 1.5.9
4. Observe that the execution stops on a different line Y

**Expected behavior:**

When the debugger is started with payload version 1.5.9, execution should stop on the line where the breakpoint was set, which is line X, as it did with payload version 1.4.0

**Actual behavior:**

When the debugger is started with payload version 1.5.9, execution stops on a different line Y.

**Notes:**

- Please let me know if you need any additional information to reproduce the issue
- This bug is blocking my ability to debug my code effectively.

**Comment by jmikrut** [comment]
Hey @DanieleDeLuis — I hear you there. It's due to our recent move from `@babel/register` to `@swc/register`. Turns out the swc sourcemaps are still ... a mystery to get to work right.

But good news - [this PR](https://github.com/payloadcms/payload/pull/1847) completely removes ANY form of register-based transpilation, and just relies on good ol' `tsc` which means that debugging is about to work again. I am going to talk with the team this morning to figure out when we plan to merge it.

There will be some breaking changes that come with that PR for non-TS users, so we have to tread carefully on this one.

Out of curiosity, do you use TS or JS? I will keep this issue open until the above PR is merged / released.
