### ISSUE TITLE
Items in a collection randomly disappear (but still in database) after migrating to Payload 1.6

### ISSUE THREAD

**Issue by MarkAtOmniux** [payloadcms/payload#2038]
# Bug Report

I started getting this really weird issue after upgrading to Payload 1.6 from 1.5.9. For context, I am using ISG with Next 13's App Directory, with a cache limit of 10 seconds while I make updates to the site for testing. I am using MongoDB Atlas, running Payload inside a Docker Container on Google Cloud Run.

I have found that when refreshing the page on my Next 13 app in quick succession, it causes Payload to freak out and hide all of the pages in my Pages collection. The data is still in Mongodb, and additionally, I can retrieve them by going to my global navbar which uses a relationship to my pages. I can then select the edit button in the relationship dropdown and save each page. This brings them all back, but it is going to be a pain to do when I have over 50 pages on my website.

I ran in the versions migration script, maybe it's an error with the new versions not playing nicely.

## Steps to Reproduce

1. Create an app using Payload 1.5.9, Create a Next 13 app using the app directory. When fetching data, set cache timeout to 10 seconds and use GraphQL.

2. Populate the CMS with pages and then upgrade Payload to the newest version.

3. Run the migration script

4. Rapidly refresh one of the pages from the NextJS frontend.

The page should eventually show a 404 error, the pages collection will show as empty on Payload but will still exist in the database.

## Other Details

Payload 1.6.5
Plugin Cloud Storage 1.0.12
Plugin Nested Docs 1.0.4
Plugin SEO 1.0.9
Next 13.1.6
Brave Browser 1.46 

UPDATE;

It looks like the request being used to fetch the data in payload is failing to get all documents due to the draft status of these documents being 'false'. 

http://localhost:8000/api/pages?locale=en&depth=0&draft=true is returning 1 document.
http://localhost:8000/api/pages?locale=en&depth=0&draft=false s returning 10 documents (these are all of the documents I am looking for).

So it seems something is going wrong with the draft versioning of these documents.

**Comment by slavanossar** [comment]
I was having this issue too, I resolved it by running 1.5.x and then saving/publishing items that were missing which seemed to fix it.

The issue I'm having now is there are items that don't actually exist listen in the collection (the last two **Home** pages don't actually exist)

<img width="992" alt="image" src="https://user-images.githubusercontent.com/7077600/217558614-e92edccb-5343-47b0-aca0-142b55ea85ff.png">

![image](https://user-images.githubusercontent.com/7077600/217559015-51293819-f300-4ff1-a942-c63631c85b6b.png)

**Comment by jmikrut** [comment]
Hey @MarkAtOmniux — just a few clarifying questions, and a bit of background info here.

In 1.6.0, we now create a corresponding version for _**every single change to a document**_, including on first creation. This allows us to do a LOT of simplification and performance enhancements within the codebase. 

Before 1.6.0, when you create a document, there would be no corresponding version created - we had only been creating versions on `update` instead of create.

And with `?draft=true`, as of 1.6.0, we literally only query the `_versions` collection. So it makes sense to me that what you're seeing could be related to the changes.

You have mentioned that you did indeed run the migration script. That script is responsible for ensuring that there is a version within the `_versions` collection for each of your documents in your main collection, so that when you query with `?draft=true` your query will return expected results.

I suspect that the script is not running properly for you. Here are a few questions:

1. What is the output when you run the script? Do you see any versions being created?
2. After running the script, do you have corresponding versions in the `_versions` collection, for each of your pages in the `pages` collection?

Let me know!

**Comment by MarkAtOmniux** [comment]
Seem like the issue was from a dodgy migration script. Ran in a new migration and actually checked the database this time and it's working as expected! :)
