### ISSUE TITLE
Customizing CSS

### ISSUE THREAD

**Issue by digital-inception** [payloadcms/payload#2049]
# Documentation Issue

I don't see ./src/admin/scss/app.scss in my Payload project as described in this documentation.
https://payloadcms.com/docs/admin/customizing-css

## Additional Details

I have my own custom developed design system that I want to integrate with Payload

**Comment by DanRibbens** [comment]
The docs are referring to files in the source code of the Payload package (https://github.com/payloadcms/payload/blob/master/src/admin/scss/app.scss). These are linked for your reference since these are the styles that your own files will be overwritting.

In your project, you can find them in the `node_modules` of your package. They are not generated for your in your own `./src` directory of your project.

Does that make sense?
I am going to close this, feel free to open if you think we can still improve our docs.

**Comment by digital-inception** [comment]
Makes 100% sense. Thanks Dan
