### ISSUE TITLE
Z-index of popup__content is lower than z-index of eyebrow navigation

### ISSUE THREAD

**Issue by jmas** [payloadcms/payload#2056]
# Bug Report

Z-index of popup__content is lower than z-index of eyebrow navigation. Examples:

<img width="1124" alt="Screenshot 2023-02-10 at 17 01 38" src="https://user-images.githubusercontent.com/90701/218125407-bbeaa81a-2aad-4e7d-94e9-96cfebeba5a4.png">

## Steps to Reproduce

1. Go to the Pages collection on the Demo website
2. Open Create New item
3. Click Add Layout
4. Carefully scroll to the position when Popup goes under the 'eyebrow' panel

## Other Details

Possible fix: increase z-index for Popup as:

```css
.popup__content {
    z-index: calc(var(--z-nav) + 1);
}
```

<img width="1512" alt="Screenshot 2023-02-10 at 17 05 52" src="https://user-images.githubusercontent.com/90701/218125925-26e8de37-db44-4466-b48d-c4b0878140d2.png">

In some cases (can't show screenshot) this bug prevents select Layout from Popup.

**Comment by JarrodMFlesch** [comment]
Hey @jmas - in the latest Payload version the blocks selector has moved to a drawer pictured below. The popup was error prone as you can see. You can either target it with your own custom CSS to fix it on your version or upgrade payload to a newer version when you have time 👍 Follow the [migration guide](https://github.com/payloadcms/payload/releases/tag/v1.6.1) here to update to the latest 1.6.x version but instead of 1.6.1 we are now on 1.6.9, but the migration is still relative.

<img width="1680" alt="blocks" src="https://user-images.githubusercontent.com/30633324/218235989-cd152e44-2c38-4b80-9448-5fde6970831e.png">

**Comment by jmas** [comment]
Thank a lot, @JarrodMFlesch !
