### ISSUE TITLE
Seeding data as published with drafts enabled makes documents dissappear from the list

### ISSUE THREAD

**Issue by davidko604** [payloadcms/payload#2113]
**# Bug Report**

When a collection is created and seeded with documents via `payload.create` with field `_status` set to `"published"` and the first change or document is saved via the payload client all the documents that were seeded disappear from the list.

When I look at the `_collection_versions` collection it has the newly saved document and only displays this one. Before this document was added it was properly displaying the seeded collection data that does not exist in the versions table.

**## Steps to Reproduce**

1. Seed multiple documents into an empty collection with `_status` `"published"`.
2. Go to payload ui list for that collection and either create or edit one of the documents then save as draft.
3. Go back to the payload ui list for that collection and all seeded documents will disappear and only the recently saved one appears.

**## Other Details**

Payload version: 1.5.7

I suspect it has something to do with seeded documents not having a "draft" version inside the versions table.

**Comment by DanRibbens** [comment]
Hi @davidko604! I believe this issue was fixed already. We made significant changes to how collections with drafts work. It will be necessary to update and follow the breaking changes, migration guide from the v1.6.0 release.

Please re-open the issue if you can reproduce the problem after updating Payload to >= v1.6.11

Thanks!
