### ISSUE TITLE
Rotated images on mac still have original orientation after upload

### ISSUE THREAD

**Issue by raffaeleparisi** [payloadcms/payload#2114]
# Bug Report

A rotated image in finder preview preserve original orientation after upload.

I assume is a image's metadata problem for macos, when editing the rotation with another software it works.

## Steps to Reproduce

1. Rotate an image in finder preview of macos
2. Upload

## Other Details

payload 1.6.11

**Comment by ChrisGV04** [comment]
Yeah, I believe this is not an issue with Payload because the same behavior occurs with almost every other third party software. Looks like the MacOS preview only stores those "preview" edits locally but it doesn't apply them to the file itself, which is very strange.

I'm not 100% sure, but at least I know that same issue occurs in a lot of tools only on MacOS. On Windows it has worked fine for me and also if you edit it on other software like Photoshop

**Comment by jmikrut** [comment]
Agreed ^ there is unfortunately little that Payload can do about this.

Bummer.

**Comment by raffaeleparisi** [comment]
It doesn't happen in wordpress so i think it should be fixed
