### ISSUE TITLE
local api CRUD operations return imprecise typing

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/payload#2128]
# Bug Report

the local api CRUD operations return imprecise typing.

## Steps to Reproduce
```ts
  const res = await payload.find({
    collection: "users",
    depth: 2,
  });

  // org will be typed `string | Organization`, but it should 
  // just be `Organization`, because depth is 2. 
  // The types do not seem to correctly infer the type.
  const org = res.docs[0].organizations
  ```
## Other Details

```
    "payload": "1.6.10",
 ```

**Comment by denolfe** [comment]
As of now depth is not taken into account for the inferred types. Therefore, they must be a union with string. We plan on improving this in the future.

**Comment by jmikrut** [comment]
Just a quick update for anyone else coming here:

Because there are a few complexities with how documents either will or will not get populated, completely outside of the `depth` argument, we are actually planning on keeping these relationship / upload field type unions as-is.

For example - access control, hooks, draft vs published, document deletion - these are just a few of the cases that could prevent a doc from being populated via depth.

For this reason it's probably best in code to always just ensure that you do have properly populated docs. This has actually helped us write better code in our own projects and is ultimately the safest type we can deliver.
