### ISSUE TITLE
link group hero path change

### ISSUE THREAD

**Issue by pcbal** [payloadcms/payload#2152]
# Bug Report

Hyphen present in link group links like path-to/document changes to path_to/document when rendered to NEXT app.

## Steps to Reproduce

collection with name xxx-yyy and render path xxx-yyy. Document linked to hero linkgroup primary/secondary link buttons. url result= xxx_yyy/document and 404 on frontend.

1.
2.
3.

**Comment by jmikrut** [comment]
We need a lot more info here to help and this sounds like a Next issue rather than a Payload issue. Right? Also, does this have to do with our own website / CMS? If so, you should open this issue with more detail on our website repo(s) instead. 

But this does not seem like a Payload issue so I will close this one.
