### ISSUE TITLE
when is upload or relation a string or number? (if ever)

### ISSUE THREAD

**Issue by chaoky** [payloadcms/payload#2213]
# Documentation Issue

The typescript definitions for `upload` and `relation` fields is always a union of the actual type and `getCollectionIDType`.
I couldn't find any documentation for when the latter would be returned

## Additional Details
```ts
//src/utilities/entityToJSONSchema.js
...
         case "upload": {
            const idFieldType = getCollectionIDType(
              config.collections,
              field.relationTo
            );
            fieldSchema = {
              oneOf: [
                {
                  type: idFieldType,
                },
                {
                  $ref: `#/definitions/${field.relationTo}`,
                },
              ],
            };
            break;
          }
...
```

**Comment by DanRibbens** [comment]
Great question. If you have a relation that hasn't been populated either because of the `depth` was met or restricted from read access control, the id will stand in place of the relation.

That will either be a string or a number depending on if the collection uses a custom id field or not.

Does that make sense?

I'm curious if you have a place you think this belongs in our docs.

**Comment by DanRibbens** [comment]
I'm going to close this for now. Feel free to comment or open a PR to improve the docs as you see fit.
