### ISSUE TITLE
Documentation should mention installing with npm option --legacy-peer-deps

### ISSUE THREAD

**Issue by jeanbmar** [payloadcms/payload#242]
# Documentation Issue

An app won't work if it was installed from scratch and dependencies were installed with `npm install` command.
Payload admin page will go nuts with React errors.
`--legacy-peer-deps` seems to be required as seen in util.js from `create-payload-app` module. 
Best would be to get rid of `--legacy-peer-deps` but docs should at least mention the option when installing payload package.

## Additional Details

I'm using Node 14.16.1 and NPM 7.17

**Comment by DanRibbens** [comment]
Before we go ahead and update the documentation, I would like to see if there are some dependency changes that need to happen to correct the underlying problem so we don't need to use `--legacy-peer-deps`. Ideally we sort it out and can remove the flag from  `util.js` of `create-payload-app`.

If somebody can take a look that would be greatly appreciated, otherwise I'll do so when I have time.

It has to do with this: https://twitter.com/wesbos/status/1359173446740172810?s=19

**Comment by Ontopic** [comment]
Use yarn 😅?

**Comment by richardvanbergen** [comment]
> Use yarn 😅?

Preach!

**Comment by josemanosalvas** [comment]
> Use yarn 😅?

Sure, but as much as I love yarn, this should at least be documented.

At the moment, the "From scratch" section in the documentation gives instructions that doesn't work.

**Comment by richardvanbergen** [comment]
I would offer to help but every time I've tried to fix peerDependencies I've ended up making things worse, so I just leave them. If anyone could enlighten me as to how you should approach fixing them I'd happily submit a pull request.

**Comment by jmikrut** [comment]
I've just gone through this and unfortunately Payload relies on a few packages that need to properly add support for React 17, but everything works properly.

So, I've just gone through and updated the docs to describe that you need to use `--legacy-peer-deps` with `npm` for now. I've requested that the offending packages add proper support and once these packages update, we'll remove this new mention from docs. 

👍
