### ISSUE TITLE
[Media] Delete button is not hidden in the media if there are no rights to change

### ISSUE THREAD

**Issue by KomlevDm** [payloadcms/payload#2428]
### Link to reproduction

simple reproduction

### To Reproduce

<img width="457" alt="image" src="https://user-images.githubusercontent.com/25402469/228856797-53ab6493-239f-47ad-9ced-0702ca06fa1b.png">

<img width="1656" alt="image" src="https://user-images.githubusercontent.com/25402469/228856468-35f18493-d9b5-4a84-966d-a6db02b7c5df.png">

### Describe the Bug

If media manipulation operations (update/delete) are disabled, then the delete button is still visible in ui. But it makes no sense, because we want to get a read-only mode for example.

### Payload Version

1.6.28

**Comment by ChrisGV04** [comment]
Oh, that's interesting. Technically setting the `access.delete: () => false` does not allow you to delete the "document" stored in the database for that media object. However, that "x" button you're referring to deletes the actual file from storage so that it can be replaced with another file. I didn't think of that before.

I do believe it shouldn't allow either of those actions as you say.
