### ISSUE TITLE
Returning `null` in a `GeneratePreviewURL` function creates type and runtime errors

### ISSUE THREAD

**Issue by evelynhathaway** [payloadcms/payload#2472]
### Link to reproduction

https://payloadcms.com/docs/configuration/collections#preview:~:text=Example%20collection%20with%20preview%20function

### To Reproduce

Use the [example preview collection function](https://payloadcms.com/docs/configuration/collections#preview:~:text=Example%20collection%20with%20preview%20function) on any collection.

### Describe the Bug

TypeScript errors on the return of `null`.

```
Type '(document: Partial<CollectionType>, { locale }: GeneratePreviewURLOptions) => string | null' is not assignable to type 'GeneratePreviewURL'.
  Type 'string | null' is not assignable to type 'string | Promise<string>'.
    Type 'null' is not assignable to type 'string | Promise<string>'.
```

The preview button still appears in the Admin UI, and clicking it opens a not found page. It tries to load the URL `null` relative to the current page, which redirects to the generic not found page for the collection.

I'd expect that the example function would not have a TypeScript issue and returning `null` would hide the button or at least let the user know that the preview is not available for the current document and its fields.

### Payload Version

1.6.28

**Comment by JessChowdhury** [comment]
Hi @evelynhathaway - I haven't been able to reproduce this on `1.6.32`, if you update to this version (payload@latest) do you still see the type error?

Definitely agree with you on the preview button, it would be great to either hide or clearly show it as disabled when you return `null` - this will likely be a feature request rather than an issue, I'll see what the team thinks here.
