### ISSUE TITLE
Too many versions created when using autosave and clicking "Revert to published"

### ISSUE THREAD

**Issue by hdodov** [payloadcms/payload#2494]
### Link to reproduction

https://github.com/hdodov/payload/tree/repro-multiple-versions

### To Reproduce

1. Create a new post
2. Write some content
3. *\*you have one version at this point**
4. Click "Publish changes"
5. *\*you now have two versions**
6. Change the content
7. Wait 2 seconds for the autosave to run
8. *\*you now have three versions**
9. Click "Revert to published"
10. *\*you now have four versions**
11. Wait 2 seconds
12. *\*you now have **five** versions**

https://user-images.githubusercontent.com/5570098/231948413-be8e59d0-6b0f-4195-9612-a0c1355a5147.mov

### Describe the Bug

Currently, Payload creates a new version even when the only difference is the status. From an editor perspective, this makes no sense and is confusing.

As you can see in the reproduction video, there were only really two versions of the document:

- one with "test" in the post's text field
- one with "test 2" in the post's text field

However, Payload displays **five** versions.

### Expected Behavior

1. Create a new post
2. Write some content
3. *\*you have one version at this point**
4. Click "Publish changes"
5. **The draft version's status changes to published, without creating a new version.**
6. *\*you still have one version**
7. Change the content
8. Wait 2 seconds for the autosave to run
9. *\*you now have two versions**
10. Click "Revert to published"
11. **Copy the previously published version's content, but change the status to "draft", so that a new version isn't created on autosave later.**
12. *\*you now have three versions**
13. Wait 2 seconds
14. **Nothing happens, because the published version already has a status of "draft", so the creation of a new version is not triggered.**
15. *\*you still have three versions**

This makes sense now. Instead of 5 versions, you now have just 3:

1. The initial one with "test"
2. The draft one with "test 2"
3. The current draft with "test", copied from the initial one

At this point, if you change the text to "test 3", you will have effectively made 3 versions and Payload would indeed have 3 versions stored in the database.

### Proposed Changes

1. When a post is published, Payload should simply change the status of the current version, rather than creating a new version where only the status is different.
2. When a post is reverted to a previously published one, the newly created draft should have its status set to "draft" upon creation, so that a new version with that status isn't created immediately after.

### Payload Version

1.6.32

**Comment by jmikrut** [comment]
Hey @hdodov — thank you for the detailed analysis! I just checked out your fork and then was able to reproduce.

I found a bug with how we were reverting to published. When we reverted to the published doc, we reset the form, but our form `reset` method did not properly set the form back to an un-modified state.

This caused a duplicative / unnecessary version, because right after you revert, the autosave will again trigger. 

However, this doesn't line up 1:1 with your suggested changes. I do see where you're coming from with your suggested changes, and my fix does indeed resolve one of the versions created, but I do think that the remaining versions are valid.

Versions should represent an accurate history of _**all changes**_ to a document, including the action of reverting to a prior published state. 

For example, if a content editor wanted to go review _**when**_ a document was published, for example, they would need to see a version that was stored when the document was published. Same with the action of when a document was reverted.

But in your 5 version scenario above, that last auto-created version was definitely not necessary because it was not a result of a user's action.

**That's the one that we have removed with the fix.**

What do you think?

**Comment by hdodov** [comment]
@jmikrut thanks a lot for the speedy fix!

I can see your point and from a technical perspective, it makes perfect sense to create a new version on each status change. But from an editor's perspective — I'm not so sure. At least for our editors. For them, a version is a change in the *content*. The status isn't actually content. It's more like meta data *about* the content.

Let's say I change the status of the document 5 times, modify something, then change it another 5 times. You would have 11 versions and only 1 of them would have actual content changes. It'd be quite painful to sift through all of them and find out the one you need.

Although it can be useful to be able to know exactly when a document has had its status changed and the state it was in when that had happened. Perhaps you should keep the current behavior and think about introducing a setting, if more people come with similar use cases to mine.
