### ISSUE TITLE
Upload field doesn't respect `access` configuration

### ISSUE THREAD

**Issue by finkinfridom** [payloadcms/payload#2535]
### Link to reproduction

https://payloadcms.com/docs/fields/upload#upload-field

### To Reproduce

```
{
  name: "templateFile",
  type: "upload",
  relationTo: "files",
  access: {
    create: function (args) {
      const { req } = args;
      if (!(req && req.user)) {
        return false;
      }
      const { user } = req;
      if (user.roles?.includes("admin")) {
        return true;
      }
      return false;
    }
  },
}
```

### Describe the Bug

In a simple scenario like this, the `upload` field is visible by the non `admin` users and they can both pick an already existing item or also create a new one.

### Payload Version

1.7.1

**Comment by JarrodMFlesch** [comment]
Hey @finkinfridom, I will attempt to reproduce this today. 

I just want to take a second and explain why we are requiring links to reproductions now. The time it takes us to setup the reproduction could be spent fixing the bug. When a reproduction is not provided we have to decipher what the collection/field configs look like and then finally get it in test environment. Sometimes a bug is not a bug when it is pulled out of the context of a users specific project — not to say that applies to this scenario, however it has happened many times before.

I think our [reproduction guide](https://github.com/payloadcms/payload/blob/master/.github/reproduction-guide.md) does a decent job getting you up and running with an environment. With that we can clone down and start diagnosing/fixing bugs much quicker.

We appreciate the issue reports from the community, but in the future will likely comment and close issues that do not have reproductions attached to them. This is not an easy decision for us because we know it feels like more work put onto  you the creator of the issue, but I think it is worth it for the sake of Payload and OSS in general. This is something we will _have_ to do and enforce upon everyone so that other issues are not created thinking that they can just ignore our reproduction requirement. 

So please, next time follow the issue template. I'll comment later today when I have more info on this specific issue 👍

**Comment by finkinfridom** [comment]
hey @JarrodMFlesch, thanks for fixing this.
I totally understand your point but seemed to me a bit overkill to completely mimic the entire environment where the issue was "simply" that the `Upload` field wasn't managing the `access` property. 
I should have reproduced the environment and then somehow added a comment/light sign to indicate something was missing. It doesn't seem an obvious way to reproduce this issue.

But please, feel free to guide us (I hope I'm not the only one here) on how to manage those scenarios.

Thanks in advance

**Comment by JarrodMFlesch** [comment]
@finkinfridom I think the issue is, we have users pasting in code examples that we cannot just throw into a blank project. So we have to strip them down to bare bones and then put them in a project. The simplest example of what was wrong in this scenario could have been communicated as:

```ts
{
  name: "templateFile",
  type: "upload",
  relationTo: "files",
  access: {
    create: () => return false,
    // update also had an issue
    // update: () => return false,
  },
}
```

But for this to work I have to ensure that I have a `files` collection set up. Which yeah is not a big deal, but I do think our `_community` folder in the test directory would have been pretty easy to throw together. Which is great, because on a simple issue like this you would have gained experience setting up a repro with our environment we talk about in our issue guide. That way when you find maybe a larger bug or something more complex, you would be able to quickly throw together an example there because you would have gained the exp from this one.

If you have any feedback on the repro guide or any ideas on how we can make it easier they are more than welcome!

Happy to have gotten this issue resolved, thanks again for reporting 👍
