### ISSUE TITLE
Percent-encoded route for admin panel renders an empty view

### ISSUE THREAD

**Issue by joas8211** [payloadcms/payload#2626]
### Link to reproduction

https://github.com/joas8211/payloadcms/tree/repro/percent-encoded-routes

### To Reproduce

1. Clone the reproduction branch.
2. Install dev dependencies using command yarn install.
3. Run the test using command `yarn playwright test test/_community`.

### Describe the Bug

If admin panel route contains special characters that are percent-encoded, the admin panel renders an empty view. I found this bug while testing special characters in tenant slug in following issue: https://github.com/joas8211/payload-tenancy/issues/12

This might be due to a bug in React Router DOM (or more specifically in it's dependecy) that was fixed for version 6 in following PR: https://github.com/remix-run/history/pull/656. Payload CMS is currently using version 5 of React Router DOM library.

### Payload Version

v1.7.5

**Comment by jacobsfletch** [comment]
Yep I completely agree, I think that's the best move. Just disallow your users from using empty space characters altogether and throw an error their way. Are you deriving this from a `slug` field or similar? You can use field-level validation in that case and automatically slugify their the value for them, here's an example of that: https://github.com/payloadcms/payload/blob/master/examples/preview/cms/src/collections/Pages/index.ts#L34

**Comment by joas8211** [comment]
Yep, I'm using a slug field value to alter the routes. I don't know if I want to enforce format other than disallow spaces... I'll continue thinking about that though.

But what I meant by last message was that Payload could throw an error when it detects a space character in routes. Or is it just better to leave it as known issue and document it?

**Comment by jacobsfletch** [comment]
@joas8211 following up here, I've actually found empty spaces _are working_ when they're _unencoded_ in your config, like this:

```ts
routes: {
  admin: '/my admin'
}
```

It gets automatically encoded by the router, so you can visit `http://localhost:3000/my%20admin`. While it is possible to adjust our schema validation, we'd need explicitly check for the `%20` special character and that may be getting a bit too specific to justify any change. Since we're simply passing the value straight into a route, I think the permanent solution is with how react-router encodes and decodes these values, instead of doing it ourselves.
