### ISSUE TITLE
The req.payloadAPI is being mutated as a side effect of getting related data

### ISSUE THREAD

**Issue by rymate1234** [payloadcms/payload#2831]
### Link to reproduction

https://github.com/rymate1234/payload/tree/bug/filtering

### To Reproduce

To reproduce this issue, attach a media file to the globals, and then perform a graphql query similar to the following:

```graphql
{
  Posts {
    docs {
      associatedMedia {
        url
      }
    }
  }
  
  Menu {
    globalAssociatedMedia {
      url
    }
  }
}
```

And notice how the logged entries are 
```
afterRead local
```

instead of 

```
afterRead GraphQL
```

### Describe the Bug

There is what I believe to be a race condition within payload that means when a large graphql query is performed, because internally it calls the local `payload.find` to resolve related fields, the `payloadAPI` gets overwritten: https://github.com/payloadcms/payload/blob/master/src/collections/operations/local/find.ts#L60

In our codebase, we have some virtual fields that return different values depending on whether it is via graphql or the cms (which is REST) and are finding this value isn't reliable.

I presume a fix might be something similar to making a local copy of `req` rather than mutating it, however I wanted to open an issue before I went ahead with a PR to do this.

### Payload Version

1.7.5, but reproduced in latest master

**Comment by jmikrut** [comment]
Hey @rymate1234 — I see the issue here. What we would need to do is populate the originating `payloadAPI` through the `dataloader` which, yes, as you noticed, does indeed use the Local API.

This shouldn't be too hard to do. We can try to get to this on this coming Monday. It will require a bit of knowledge about the whole Payload picture, and we should probably have some tests to confirm that this works, but we're happy to tackle this.

Stay tuned!

**Comment by jmikrut** [comment]
Hey @rymate1234 — this is now fixed. It will be released with our next patch version due shortly!
