### ISSUE TITLE
Relationship hasMany and fiterOptions fails with more than 10 items

### ISSUE THREAD

**Issue by Grandnainconnu** [payloadcms/payload#2860]
### Link to reproduction

https://codesandbox.io/p/sandbox/cranky-chebyshev-rkppjr

### To Reproduce

Open the sandbox link and you can fetch `{url}/seed` - that will initialize the user `test@test.com` with password `test`.
In the `Examples` collection, there are all the entries and the main one `Main test`.

You can add the last document to the `references` relationship, and then hit `Save`.

### Describe the Bug

When having a (self referencing) relationship `hasMany` with `filterOptions`, it fails to save more than 10 values.
It appears from `1.7` (first encounter) up to `1.9.5` that is the version used on the sandbox. 

Removing the `filterOptions` allows it to save properly, but that's not the goal.

### Payload Version

1.9.5

**Comment by DanRibbens** [comment]
I'm not sure the codesandbox is working correctly for me. I tried and couldn't get to a point where I had seeded the data and was able to reproduce the issue.

I did try and reproduce the issue in the Payload repo's test setup and was unable. It could be that the fix is handled by in https://github.com/payloadcms/payload/pull/2871, but without being able to reproduce it, I'm not sure.

I'd like it if you could try and reproduce it again on the latest version of Payload, working on releasing 1.10.0 right now.

**Comment by Grandnainconnu** [comment]
https://github.com/payloadcms/payload/assets/4025637/6ae318b4-21ea-4bb5-b485-555a7f6cd330

Don't know if that can help, I'll try with 1.10 though! Thank you

**Comment by DanRibbens** [comment]
Alright, `1.10.0` is released now. Go ahead and update here when you get a chance.

Thanks!

**Comment by Grandnainconnu** [comment]
Still no luck, after updating the dependencies and trying again :/

**Comment by DanRibbens** [comment]
Hey @Grandnainconnu, the video was really helpful.

I loved that you were able to run it in codesandbox, but it wasn't seeding for me. Now I don't need it.

I'm working on a patch release for this right now.

**Comment by DanRibbens** [comment]
Releas v1.10.1 should address this issue. Please reopen if it isn't resolved after you update.

Thanks!

**Comment by Grandnainconnu** [comment]
It indeed resolved the problem! Thank you for your work!
