### ISSUE TITLE
Bundle size too large, takes 30s to load.

### ISSUE THREAD

**Issue by Stupidism** [payloadcms/payload#2947]
### Link to reproduction

Not for now

### To Reproduce

Check the bundle size of the web app

<img width="1016" alt="image" src="https://github.com/payloadcms/payload/assets/5801015/e9d0cbaa-19f7-4084-a559-b3e6f9383fcc">

### Describe the Bug

Bundle just too large. takes 30s to load

### Payload Version

1.9.5

**Comment by jmikrut** [comment]
Hey @Stupidism, this is not an issue with Payload.

It's because you're running in dev mode and not production. In dev mode, Webpack does not optimize your JS bundle for filesize and it loads up your code with sourcemaps, hot module reloading, and lots more.

Running in production, Payload is already quite well-optimized coming in at around ~660kb.

<img width="1728" alt="Screen Shot 2023-06-30 at 7 05 38 AM" src="https://github.com/payloadcms/payload/assets/6651896/fa77c3c6-2644-400a-8a5b-6487f75c126d">

Make sure you are running production with `NODE_ENV=production`.

**Comment by JarrodMFlesch** [comment]
I am not sure exactly what is going on, but I do know that setting `NODE_ENV=production` will opt out of webpack entirely as you can see [here](https://github.com/payloadcms/payload/blob/master/src/express/admin.ts#L13).

Setting NODE_ENV=production _is how you opt out_ of webpack. You should see the bundle size drastically decrease and the webpack hmr should not show in your network panel.
