### ISSUE TITLE
Bulk delete still enabled, even though access.delete is set to false

### ISSUE THREAD

**Issue by rrums123** [payloadcms/payload#2950]
### Link to reproduction

-

### To Reproduce

I conditionally set `access.delete` in collection. All good in Edit page, delete button was not appear, but in List page I still able to do bulk delete

Edit page
<img width="1254" alt="Screenshot 2023-06-30 at 20 57 23" src="https://github.com/payloadcms/payload/assets/100153954/dc90b244-96fd-4526-916c-b8041d03891f">

List page
<img width="1194" alt="Screenshot 2023-06-30 at 20 57 15" src="https://github.com/payloadcms/payload/assets/100153954/e77c4422-b67d-4d5a-92e4-95811480cc7a">

### Describe the Bug

These documents should not be able to removed.

### Payload Version

1.10.2

**Comment by DanRibbens** [comment]
Hi @rrums123,

When I first read your issue I was worried we had a major issue with our access control. After testing, it seems that documents are prevented from being deleted and that the issue you're reporting is only a UX issue where the delete control is available when it might not be possible to perform the action. 

I tested with the following scenarios to be certain that our access control was behaving correctly.

1. `delete: () => false` there is no delete control.
2. `delete: ({ req }) => (req.user.email === 'dev@payloadcms.com')` when logged in as dev@payloadcms.com I had the option to delete, but when I changed my email to something that didn't, I was not given the option to bulk delete.
3. `delete: () => ({ name: { equals: 'delete' } })` This is the scenario I believe you must have encountered. There is not a good way for the frontend UI to present the delete option or not since a DB query must be performed to know if the documents selected should be allowed to be deleted.

If you attempt to delete under that 3rd scenario, you do get the correct output that says how many documents were able to be deleted.

I don't think there is an issue here. If I've misunderstood the problem you're reporting, please re-open.
If there is something else we can improve in this workflow, I'd be very interested in your ideas.

**Comment by rrums123** [comment]
Aha. I think I know why.
This is the code:
```
delete: async ({ req, id }) => {
            if (id) {
                const page = await req.payload.findByID({
                    collection: 'ui-pages',
                    id
                });

                const tests = await req.payload.find({
                    collection: 'tests',
                    where: {
                        page: {
                            equals: id
                        }
                    }
                })

                return !(page?.fallback || tests.totalDocs > 0);
            }

            return true
        }
```

My condition depends on ID.
I just realized that ID was not present when in List page. Is there any way to handle this?

**Comment by DanRibbens** [comment]
> I think I will set to return false by default, to not allow bulk delete

Ideally we would have a way to prevent the UI from having the bulk delete option for a collection. For now, you'll have to do it through access control.
