### ISSUE TITLE
Filter state out of sync when loading a collection URL with search params

### ISSUE THREAD

**Issue by thgh** [payloadcms/payload#3082]
### Link to reproduction

/admin/collections/widgets?where[tenant][equals]=example

### To Reproduce

Filter state out of sync: `/admin/collections/widgets?where[tenant][equals]=example` 
Works as expected: `/admin/collections/widgets?where[or][0][and][0][tenant][equals]=example`

### Describe the Bug

Changing the filters on a collection page updates the URL, that is great. The URL is a little more complex than needed though. And when linking to a filtered collection in a simple way, breaks the filter state: the collection is filtered, but the UI does not indicate that a filter is active which is confusing.

### Payload Version

1.11.3

**Comment by AlessioGr** [comment]
@thgh thank you for reporting this! Currently, the WhereBuilder in the collection's list view only accepts Where queries which fit the specific `[or][and]` format because that's what the component needs in order to parse it.

I've opened a PR #3087 which will fix this issue by transforming simpler queries, like `[tenant][equals]=example` into that format :)
