### ISSUE TITLE
Unexpected sorting results for virtual fields

### ISSUE THREAD

**Issue by DrMint** [payloadcms/payload#3098]
### Link to reproduction

https://github.com/DrMint/payload-virtual-field-sort-bug-report

### To Reproduce

- Clone https://github.com/DrMint/payload-virtual-field-sort-bug-report
- `npm i`
- `npm run dev _community`
- Go to http://localhost:3000/admin/collections/posts
- Sort by `virtual` (the name of the virtual field), ascending order

### Describe the Bug

The value of the `virtual` field is set to be equal to the `text` field. As such, it would be expected that sorting using the `virtual` field would give the same result as sorting by the `text` field.

However, the result is completely different. It seems to be the same result as if we are sorting by id (ascending order). Sorting the virtual field by ascending or descending order doesn't actually change the result.

![image](https://github.com/payloadcms/payload/assets/29893320/a237c3d1-7c16-4f4d-833e-c688e1a15794)

Furthermore, when pagination occurs (you can set the results per page to 5), we get a different order, which is still different from sorting using the `text` field.

![image](https://github.com/payloadcms/payload/assets/29893320/66dc2d06-3270-44b4-a225-508b152b6243)

### Payload Version

1.11.7

**Comment by DanRibbens** [comment]
Hi @DrMint,

Thanks for reporting! I think this is not a bug but something we could improve documentation for instead. I'll first describe why it isn't a bug and then we can figure out if there is anything we can do to help make it more understandable.

Sorting and pagination is handled by the database and your virtual field is not being stored there and so it cannot be properly sorted. There isn't a way that the Payload operation could return sorted results in a consistent way from a virtual field. We don't do any sorting on results in the server code at all since it is already handled by the database.

If we tried to do it in the application, the server would have to fetch 100% of the collection from the database, iterate through hooks and then sort them in the operation. Obviously, this isn't desirable for performance and would crash on any decently sized collections.

If you need to sort on a field it must be persisted to the database. I think this is pretty reasonable and expected behavior.

Does that make sense?

I'm going to close your issue, but feel free to open it if there is something we can do.

**Comment by DrMint** [comment]
Hi @DanRibbens,

Thank you for the explanation! Yes I think it makes perfect sense. I guess I didn't take the time to think about how the sort really works, I just saw the mismatch between how the collection is configured and the behavior observed in the admin UI.

Yes I think it could be mentioned somewhere in the doc. I've seen some folks mentioning custom sorting in the community-help channel on the Discord server, and knowing what I know now, it makes sense why this isn't really possible unless a value is stored in the database.

I followed this blog post (https://payloadcms.com/blog/learn-how-virtual-fields-can-help-solve-common-cms-challenges) to implement the virtual field. Maybe there could be a "Limitations" section where this is address.

Maybe it could be mentioned here too (https://payloadcms.com/docs/configuration/collections#options) in the description of the `defaultSort`.

Lastly, I think the most misleading here is that there are sorting options on the column of the list view for a virtual field. We could imagine having an option in the admin property of a field to disable sorting. `isSortable` is already a field for relationships and select fields, so I'm not sure what the naming of such property should be. Or maybe the concept of "virtual field" should be more explicitly defined (a `isVirtual` option that would take care of these UI changes?).

By the way, I was reading this in the documentation (https://payloadcms.com/docs/configuration/collections#list-searchable-fields): 
> In the List view, there is a "search" box that allows you to quickly find a document with a search. By default, it searches on the ID field. If you have admin.useAsTitle defined, the list search will use that field.

I haven't tried but my guess is searching is also handled by the database, isn't it? And as such, if the field used as title is a virtual field, the search function won't work because it can't be indexed by the database? Creating a virtual field to be used as the title seems like a reasonable use-case, I wonder if this could be mentioned that `admin.listSearchableFields` needs to be set and include indexable field(s) when using a virtual field as the title.
