### ISSUE TITLE
generate:graphQLSchema script ignores .env, causes payload config parsing to fail

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#3330]
### Link to reproduction

N/A

### To Reproduce

0. Generate a payload project
1. Specify `MY_VAR=my_value` in `.env`
2. Add this line to `payload.config.ts`: `console.assert(process.env.MY_VAR, 'env var not set');`
3. Run `yarn payload generate:graphQLSchema`
4. The assertion will fail.

### Describe the Bug

For some reason, `generate:graphQLSchema` does not respect the `.env` values set.

### Payload Version

1.15.6

**Comment by JessChowdhury** [comment]
If you add `require('dotenv').config();` to your `payload.config.ts` then try the steps again - does it work?

To load the environment variables, you need the `dotenv` package to be initiated - this usually happens in `server.ts` when Payload starts up. Since `yarn generate:graphQLSchema` doesn't call this file, you would need to redeclare the package to access the envs.

Does this help?

**Comment by tyteen4a03** [comment]
Yes, but it smells like an oversight on Payload's part not to load `.env`, especially as setting things up in Payload config is such a common paradigm (e.g. oauth)
