### ISSUE TITLE
Collection stuck on load after pressing a "sort" button

### ISSUE THREAD

**Issue by weareturnone** [payloadcms/payload#3399]
### Link to reproduction

-

### To Reproduce

When pressing a "sort" button in a CMS collection, the screen stays on "load" logging in and out etc did not work. 

![CleanShot 2023-09-27 at 20 52 54](https://github.com/payloadcms/payload/assets/106660686/e804bd79-4baf-4d13-bb91-37d0d29c6128)
![CleanShot 2023-09-27 at 20 52 45](https://github.com/payloadcms/payload/assets/106660686/69020882-b28c-4400-b7ef-24bfce90a5b4)

### Describe the Bug

CMS Collection stays on load after pressing a "sort" property. Hope this helps with reproduction!

### Payload Version

1.15.6

**Comment by jmikrut** [comment]
Hey @weareturnone — what is `lockdown-install`? We will need to have a reproducible example to replicate in order to fix this one. Also, does the problem persist in 2.0? If you continue to see this error, please re-open this issue and add a reproduction step as we cannot reproduce. Happy to look into it if we can reproduce though.

Thank you!

**Comment by Bohooslav** [comment]
When I try to sort by field which is object (location in this case) it fails to load... Payload v2.19.2
![image](https://github.com/payloadcms/payload/assets/35796539/0f201ba8-c482-44da-98ac-5c163d6b1b7d)
