### ISSUE TITLE
Postgres: select field with hasMany in group not working

### ISSUE THREAD

**Issue by Janisvb** [payloadcms/payload#3570]
### Link to reproduction

https://github.com/janisvb/payload-reproduction/tree/group-select-hasmany

### To Reproduce

```
export PAYLOAD_DATABASE=postgres
yarn dev _community
```

### Describe the Bug

A select field with `hasMany: true` inside a group field is not working with Postgres. It works fine with MongoDB and outside a group field: 

https://github.com/payloadcms/payload/assets/7983986/f3caa002-b44f-45e9-87b3-f432f641d91b

The error is
```
TypeError: Cannot read properties of undefined (reading 'parent')
    at upsertRow (/packages/db-postgres/src/upsertRow/index.ts:262:57)
```

Additionally, I think the table name for holding the select values is longer than needed (`posts_settings_settings_category` instead of `posts_settings_category`). We have a case with a select field inside two groups, where the table name is longer than the 63 character limit of Postgres. This leads to unexpected errors.

### Payload Version

2.0.4

### Adapters and Plugins

db-postgres, bundler-webpack

**Comment by jmikrut** [comment]
Oh I forgot - one more comment here:

> Additionally, I think the table name for holding the select values is longer than needed (posts_settings_settings_category instead of posts_settings_category)

So, the reason we name that table in that way is because there could be naming conflicts if we did not. For example, if you had a `category` field at the top level of your schema, and also had one within your `settings` group - there would be a conflict. 

The way we plan to fix this in the future is to allow you to _**override**_ or manually specify your table names on a collection / block / array - based approach right in the Payload config. So this is something that you will be able to do in the future, but yes, for now, your table names can probably get pretty long. It's up to you to take that into consideration when you model your schemas for the time being. And then once we release support for manually defining table names, you'll be able to leverage that and use migrations accordingly!

How's that?

**Comment by Janisvb** [comment]
Sounds good, thanks for the explanation.
