### ISSUE TITLE
Unable to re-upload existing images to the same collection

### ISSUE THREAD

**Issue by richardvanbergen** [payloadcms/payload#358]
# Bug Report

Unable to re-upload existing images to the same collection. Receive validation error: "The following field is invalid: filename"

I've currently on verified this on my production environment. I'll provide more information when I get a chance to debug it locally.

## Expected Behavior

Should be able to upload the same file twice to the same collection. Or at least give proper validation message back.

## Steps to Reproduce

1. Create new collection with upload specified.
2. Upload an image
3. Upload a second image using the same file as before
4. Unable to upload image

## Detailed Description

Payload version 0.11.0

**Comment by jmikrut** [comment]
Hey @richardvanbergen — thank you for bringing this one up!

What's happening is that when we go to ensure that the filenames being uploaded are "safe", we check the filesystem only. If the file exists in the filesystem, we increment the filename and then proceed with the newly incremented filename so as not to replace the existing file. 

In your case, you did not have a local file, as I'm imagining you've uploaded to S3 permanent storage and then deleted the local file. But, you still had an old database record with the same filename. 

Mongo then enforced that the filename should be unique.

 We need to do 2 things:

1. improve the error message coming back from the backend saying that the `filename` must be unique - rather than just simply saying that the field is invalid
2. check the _**database**_ and the filesystem for an existing filename and increment if either are found

This should solve it.

What do you think?

**Comment by richardvanbergen** [comment]
Yes I hope so, you seem to have a pretty good handle on it. I still haven't had the time to debug it locally as I've got a huge backlog at the moment. Did you manage to reproduce?

**Comment by jmikrut** [comment]
Yep I reproduced with the scenario above. No need to debug on your end — I'm quite confident that this is the issue. Working on getting a fix for it in place shortly.

Thanks once again for pointing this out!

**Comment by richardvanbergen** [comment]
@jeanbmar Thanks I'll give it a shot. I'm in the middle of adding cloudinary support to my plugin but I'll try after then.

Probably should be fixed in the core though 😉

**Comment by jmikrut** [comment]
Nailed it. Thanks for hanging in here on this one—we've got some big stuff in the works that has been taking priority, including type generation, revisions, drafts, and more. 

But in a0fb48c, we now check for an existing doc OR an existing file, and increment names accordingly. This is now fixed!

**Comment by richardvanbergen** [comment]
> drafts

@jmikrut  No worries at all, drafts are **so** important for us I don't mind waiting for stuff like this. Unfortunately, I think this had another side effect, which I've filed another bug for.
