### ISSUE TITLE
Where did docs on Layout go?

### ISSUE THREAD

**Issue by jinalskothari** [payloadcms/payload#3621]
# Documentation Issue
 
Can no longer find documentation on the Layout field.

**Comment by jmikrut** [comment]
What is the Layout field? Do you mean Blocks?

We never had a Layout field, but here's the docs to the Blocks field:

https://payloadcms.com/docs/fields/blocks#blocks-field

Also, please try and leverage Issues for bugs and problems with the Payload codebase. Try and point your questions to the Discussions if you can - that helps us organize and prioritize. I really appreciate it!

**Comment by jinalskothari** [comment]
The Layout feature is an important one obviously. It should not hide inside the Blocks documentation but should have an existence somewhere top level in the docs.

**Comment by purenofuss** [comment]
[jinalskothari](https://github.com/jinalskothari) I highly recommend joining payload's discord, you can find the invite in the to right corner of https://payloadcms.com. Payload has a very helpfull community. Anyways, I think blocks is the correct name since blocks can be used in multiple fields like hero, header, layout, and more.
