### ISSUE TITLE
Custom endpoints ignore `limit: 0` inside payload.find

### ISSUE THREAD

**Issue by Arctomachine** [payloadcms/payload#3641]
### Link to reproduction

https://github.com/Arctomachine/payload-bug-custom-endpoints

### To Reproduce

1. Start dev server
2. Log in, go to collection `items` and create at least 11 items (should be 2+ pages in collection list view by default)
3. Make request to `/api/items/get-all`

### Describe the Bug

Should get 1 page with all items. Instead only gets first page with 10 items

### Payload Version

2.0.5

### Adapters and Plugins

Webpack, mongo

**Comment by jmikrut** [comment]
Hey @Arctomachine — thanks for bringing this up. You just need to pass `pagination: false`, which was an undocumented Local API `find` method property. I've just documented it. Give that a shot and then it will work as you expect!

Thanks!

**Comment by Haliax** [comment]
This also affects the RestAPI.

The `limit=0` was working before v2. The LokalAPI fix does not resolve the issue in our case.

**Comment by Haliax** [comment]
This also affects the RestAPI.
The `limit=0` was working before v2. The LokalAPI fix does not resolve the issue in our case.

Should I open another issue for or do you want to reopen this issue, @jmikrut ?

**Comment by jmikrut** [comment]
Hey @Haliax are you sure this was working in 2.0? I believe we had this intentionally disabled because it could potentially open up the door for malicious API abuse if you have lots of records. 

I do believe in any case that this should not be possible by default through REST or GraphQL.

We could add a way to enable this functionality via those APIs. 

If you are interested in that, maybe open a Feature Request discussion and we could go from there?

Does that make sense?

**Comment by Haliax** [comment]
I wanted to say that it worked before changing to v2. Sorry for the confusion.

I see your point! But on the other hand, you are still allowing requests like `limit=99999`.
For our use-case, it is good to have this workaround. Better would be to allow requests like that for authorized API users.

I will create a feature request for that.

**Comment by mvarendorff** [comment]
Yeah, this suddenly became an undocumented breaking change for us. We relied on a graphql resolver to return the full list of documents when requested with `limit: 0` and after the upgrade to v2, our list contained a fixed 10 items instead of 120. We'll fall back to Haliax' workaround with a high limit for now.
