### ISSUE TITLE
plugin-nested-docs: The imports from Overrides doesn't work

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#3690]
The given example at Overrides section doesn't work.

```ts
import createParentField from "@payloadcms/plugin-nested-docs/fields/parent";
```

Generates: `Cannot find module '@payloadcms/plugin-nested-docs/fields/parent' or its corresponding type declarations`

Instead, a working version would be:

```ts
import createParentField from "@payloadcms/plugin-nested-docs/dist/fields/parent";
```

**Comment by DanRibbens** [comment]
Related: https://github.com/payloadcms/payload/issues/3692

**Comment by DanRibbens** [comment]
You are importing as if these were default exports. Instead of `import createParentField from "@payloadcms/plugin-nested-docs/fields"`, you need to have createParentField inside of `{ }` like this:

```import { createParentField } from "@payloadcms/plugin-nested-docs/fields"```

This is how it written in the overrides section of the docs.

I'll address your other concerns in the other open issue #3692 aside from this one: 

> It seems like the plugin is creating some virtual fields, but I don't find anything in the docs about these fields. I have questions like:
Can the `breadcrumb' field in a collection override the Admin StepNav?

That is not currently possible. There isn't a way right now for items in the step nav to be this dynamic. I think that would be an interesting feature but require a bit of planning to design the feature. Then it would be possible for this plugin to be extended to do what you are asking which would be very nice.
