### ISSUE TITLE
Support running migrations in prod environment

### ISSUE THREAD

**Issue by dacgray** [payloadcms/payload#3746]
The release migration docs don't work in a prod environment when using the docker image - in our case deployed to ECS.

## Additional Details

- cross-env is missing
- the `"payload": "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts payload",` needs to be `"payload": "cross-env PAYLOAD_CONFIG_PATH=dist/payload.config.js payload",`
- it doesn't find migrations in the `dist/migrations`

I'm sure there is a better way, but these steps ended up working for me when execing into a prod task:

- npm i -g cross-env
- manually edited the package.json payload script
- manually added .env (not sure if this is needed)
- manually added `src/migrations/versions_v1_v2.ts`
- ran `yarn payload migrate`

---

Would be very helpful to have the 2.0.0 release docs updated on how to simply run migrations in a prod env.

As mentioned here: https://github.com/payloadcms/payload/issues/3735  would be best to just get the migration file from the link instead of worrying about package managers.

**Comment by DavidOliver** [comment]
To get migrations to run automatically in a Docker container, here's what [I've stumbled into](https://discord.com/channels/967097582721572934/1169193360465080370/1172062256171843705) doing for the time being:

```diff
diff --git a/payload/Dockerfile b/payload/Dockerfile
--- a/payload/Dockerfile
+++ b/payload/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:18.8-alpine as base
+FROM node:20-alpine as base
 
 FROM base as builder
 
@@ -20,7 +20,9 @@ COPY package*.json  ./
 RUN npm install --production
 COPY --from=builder /home/node/app/dist ./dist
 COPY --from=builder /home/node/app/build ./build
+COPY src/migrations ./src/migrations
 
 EXPOSE 3000
 
-CMD ["node", "dist/server.js"]
+CMD ["npm", "run", "serve"]
```

The new `COPY` puts the (ts) migrations in `src`, where the migration command finds them.

(Updating to node:20-alpine got rid of a warning about Fetch, if I remember correctly.)

And my `package.json` scripts are as follows:

```json
  "scripts": {
    "dev": "nodemon",
    "build:payload": "payload build",
    "build:server": "tsc",
    "build": "npm run copyfiles && npm run build:payload && npm run build:server",
    "preserve": "npm run migrations:run",
    "serve": "NODE_ENV=production node dist/server.js",
    "copyfiles": "copyfiles -u 1 \"src/**/*.{html,css,scss,ttf,woff,woff2,eot,svg,jpg,png}\" dist/",
    "payload": "payload",
    "migrations:create": "payload migrate:create",
    "migrations:run": "payload migrate",
    "generate:types": "payload generate:types",
    "generate:graphQLSchema": "payload generate:graphQLSchema"
  }
```

The `preserve` (pre-serve) script is run before `serve`, and runs a script that runs `payload migrate`.

I added `migrations:create|run` convenience scripts so that the actual commands are stated upfront.

I found I could remove all of the setting of the `PAYLOAD_CONFIG_PATH` env var, which differs in js/ts-dev/prod, without anything bad seeming to happen in either dev or prod.

**Comment by denolfe** [comment]
Our migrations should support both typescript migrations and the compiled versions of those - .js files inside a dist dir or similar. Working on adding support for this now.
