### ISSUE TITLE
Live preview `Uncaught SyntaxError: "[object Object]" is not valid JSON`

### ISSUE THREAD

**Issue by DennisSnijder** [payloadcms/payload#3779]
### Describe the Bug

When using certain chrome extensions (react devtools extension, facebook pixel extension etc) the live-preview package will throw the following exceptions `Uncaught SyntaxError: "[object Object]" is not valid JSON`.

Upon further investigation, it is due to the extensions sending "message" events into the browser and the `live-preview` package trying to always parse the data it receives from the event.

![Screenshot 2023-10-20 at 11 01 46](https://github.com/payloadcms/payload/assets/6953846/a9c2cbaa-2b9c-42bc-aa20-321f1b37d1ed)

In the above example (chrome debugging tool) it tries to `JSON.parse` an object received from the react-devtools extension.

https://github.com/payloadcms/payload/blob/main/packages/live-preview/src/handleMessage.ts#L17

### To Reproduce

Install the react devtools chrome extensions and try to use live preview. 
https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi

### Payload Version

2.0.10

**Comment by jainkunal40** [comment]
Will give it a try, Can you please assign this to me?

**Comment by jacobsfletch** [comment]
The changes by @dkirchhof in #3791 was the fix for this 🥳. The JSON parsing in the screenshot happens within the admin panel when it attempts to receive the "ready" event from your app. Although the package itself listens for and parses messages in the same way (linked above), it already safely does by checking the origin of the event before parsing. Thank you [DennisSnijder](https://github.com/DennisSnijder) for the initial reporting on this. I'm going to close this out which will included in the next release. And [jainkunal40](https://github.com/jainkunal40) I'm going to leave some feedback on your PR right now too (#3781).

**Comment by cbratschi** [comment]
I still have this issue in the latest Payload version 2.0.15.

**Comment by yootravel** [comment]
I'm having the same problem with the current version 2.6.0

**Comment by jacobsfletch** [comment]
@cbratschi @yootravel is this still an issue for you? I'm unable to recreate this since posting the fix. I have React Developer Tools installed in my Chrome browser, along with the following package versions:

```json
{
  "dependencies": {
    "payload": "2.24.1",
    "@payloadcms/live-preview": "0.2.2",
    "@payloadcms/live-preview-react": "0.2.0"
  }
}
```

**Comment by yootravel** [comment]
No we don't have that problem anymore,, thank you

**Comment by cbratschi** [comment]
It works here too. Thanks.
