### ISSUE TITLE
Live-preview package causes client side error in traverseFields

### ISSUE THREAD

**Issue by Cuzart** [payloadcms/payload#3806]
### Describe the Bug

I am sure this is still wip but this is causing a client side error on my project which is blocking me rn. I first noticed this error after clearing my pnpm cache and reinstalling all modules. The error is thrown when I open my NextJS frontend (live-preview and draft preview is not affected). The error is thrown in the traverseFields file from the live-preview package
`traverseFields.js:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')
    at traverseFields (traverseFields.js:15:1)
    at mergeData (mergeData.js:17:1)
    at handleMessage (handleMessage.js:29:1)
    at onMessage (subscribe.js:17:1)`
After some digging in the source code I have noticed that this happens because fieldSchema is undefined and forEach is called anyway. I was able to fix this locally by catching the undefined case `fieldSchema?.forEach(...)` in [line 24](https://github.com/payloadcms/payload/blob/main/packages/live-preview/src/traverseFields.ts) but I also thought that this code should not be called in the first place so there might be a bug in the conditions in the [handleMessage](https://github.com/payloadcms/payload/blob/main/packages/live-preview/src/handleMessage.ts) file which is calling the traverseFields eventually. This is only my assumption I hope it helps in fixing this issue.

EDIT: 
I also found out that a similar problem occurs if you got for example the [MetaMask](https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=de) browser extension activated on Chromium. There is a runtime error happening in handleMessage file of the same package because it also makes use of a MessageEvent. The error occurs when trying to JSON.parse the data field of the MessageEvent.
<img width="246" alt="Bildschirmfoto 2023-10-24 um 17 23 53" src="https://github.com/payloadcms/payload/assets/60718229/b30f81d2-45d2-473b-9bc6-280e519bb700">

### To Reproduce

Really not sure how to reproduce this behaviour. Because it only happened after reinstalling my node_modules. I tried to use a fresh mongoDB table to make sure it wasn't my data causing this. I am using webpack, lexical, mongodb, NextJS custom server, drafts and live-preview. Sorry for the lack of information on the reproduction I hope pointing out the files from the source code helped.

### Payload Version

2.0.11 and 1.0.5 for live-preview-react

**Comment by thompsonsj** [comment]
I'm getting the same.

<img width="779" alt="Screenshot 2023-10-27 at 10 34 29" src="https://github.com/payloadcms/payload/assets/44806974/1a51cc48-b0c3-4df6-b5a5-920f6478c632">
<img width="756" alt="Screenshot 2023-10-27 at 10 37 10" src="https://github.com/payloadcms/payload/assets/44806974/e16338ed-0d1b-4f22-b11e-5a626af53c49">

Strangely, if I click to open the live preview in a separate window, it works fine!

**Comment by arieltonglet** [comment]
Same here! I though that it has something to do with next-payload.
For me, it is triggering the error only when I open the page directly (in dev mode).
Live preview is working fine, docked or separate window.

**Payload Version**
2.0.13

**Adapters and Plugins**
@payloadcms/live-preview-react 0.1.5
@payloadcms/next-payload 0.1.8

**Comment by HarleySalas** [comment]
I had a project with payload hosted separately. I created a project with the `website` template and copy pasted my nextjs code in. 

What worked completely fine in my old project resulted in this same error now. I wasn't even using the live preview function. Why does it even do **anything** when live-preview is not even being used? Why does it behave differently inside monorepo?

**Comment by jacobsfletch** [comment]
Hey @Cuzart and everyone, I just opened up PR #4074 which will prevent this error from throwing, but this doesn't necessarily solve for _why_ the field schema is missing in the first place for some of you. Before traversing fields and merging data, we dispatch a post message event to deliver the schema to your front-end _one time_. It could be that this delivery failed, and then subsequent events are missing the field schema, as you're seeing. 

@thompsonsj the fact that it's works again when opening in a new window, is probably because we are re-delivering the field schema again.

@arieltonglet the fact that you are only seeing this error when accessing the page directly feels odd. Can you confirm that this is true? Because on direct access of your site, there is no parent window at all to even send message events from in the first place.

@HarleySalas I'm not sure I'm following. Can you be explain your scenario a bit more?

**Comment by arieltonglet** [comment]
Hi @jacobsfletch, thanks a lot for the fix!
In the past days I was working in other parts of this project and had to reinstall node_modules, among a lot of changes in collections and other stuff – I'm saying this because of @Cuzart original post, where he said this only happened after reinstalling node_modules.

I've tested now again, and the live preview is working fine (at some point I was getting this error in the preview as well), but accessing the page directly is still triggering this error. I'll try to reproduce this in a fresh project tomorrow to see if I can find out what's happening. Thanks again!

**Comment by arieltonglet** [comment]
Hey @jacobsfletch
I was able to reproduce the error in this repo:
https://github.com/arieltonglet/payload-test-traverse


https://github.com/payloadcms/payload/assets/13951624/e477dbf2-ab28-4a4a-9281-edb669e7b530

**Comment by HarleySalas** [comment]
> @HarleySalas I'm not sure I'm following. Can you be explain your scenario a bit more?

What I'm saying is that I did not experience the issue when payload was deployed separately from my nextjs frontend. I only encountered this issue after switching to a monorepo and hosting them together.

I was just expressing how odd it was to me that the error occurs, even when the payload admin is not open. I understand if live-preview has a bug, but if I'm not even using the live-preview feature, it's quite odd that it is still *trying* to work, or do **something**.

I can also confirm as well, in my instance, the error occurs both when the website is open by itself **and* when you use the `live-preview` feature, with an iframe.

**Comment by Cuzart** [comment]
Thanks for the fix @jacobsfletch. Although as you already said this does not prevent the why. As you said the cause is a missing schema but why is the schema even requested when I only request my frontend this has nothing to do with live-preview at all and it should not evoke code within the live-preview package. I got the supposition that hosting my frontend and payload on the same server and same port (next-custom server) may cause this but I have no idea how to avoid this and I feel like this code should not be run at all in this context.
