### ISSUE TITLE
Custom Dashboard Icon does not persist to List view

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#3905]
### Link to reproduction

https://github.com/payloadcms/payload/tree/recreate/missing-dashboard-icon

### Describe the Bug

When setting a custom dashboard icon, it disappears upon entering any collection (list view).

https://github.com/payloadcms/payload/assets/65888/339b703f-3e63-46a1-8112-0b50ff5b8393

### To Reproduce

- Load above branch
- Open admin, see custom icon in top left
- Open a collection list view
- Observe the icon disappear

### Payload Version

2.0.13

### Adapters and Plugins

NA

**Comment by jacobsfletch** [comment]
@denolfe the problem here is that your SVG has no `width` or `height` attribute. This SVG is rendered within a flexbox, and without those attributes, shrinks to `0` width. This is just the web standard afaik and there is no way around this behavior. Since this is a custom icon, I don't think we should explicitly set the width or height, this way the user can size their icon to whatever they need. I don't think we should add `min-width` here either, because this causes inconsistent sizing.

So here's the fix:

```ts
// `admin.graphics.Icon`
<svg
  width="1.5em" // Add this
  height="1.5em" // This too
  viewBox="0 0 24 24"
>
```

**Comment by denolfe** [comment]
Thanks @jacobsfletch. Updated the [Discord Thread](https://discord.com/channels/967097582721572934/1167529824470970460)
