### ISSUE TITLE
pnpm cannot find react module

### ISSUE THREAD

**Issue by GeorgeHulpoi** [payloadcms/payload#3932]
### Link to reproduction

https://github.com/GeorgeHulpoi/payload-pnpm-not-found-react

### Describe the Bug

Building with `pnpm` throws an error that it can't find `react`, but it does not happen with `npm`.

### To Reproduce

1. `pnpm install`
2. `pnpm build`

### Payload Version

2.0.13

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by denolfe** [comment]
This feels expected to me. The project doesn't explicitly install `react` and you're attempting to reference it.

It sounds like `npm` is a bit more loose with what you can reference. I assume it is just picking up `react` if any other dependency install it.

Will reopen if I misunderstood.

**Comment by Swahjak** [comment]
He @denolfe I'm confused as to why you feel this is expected. It seems like the provided repo is a 'blank' (from template) payload project which doesn't build when using pnpm. I would assume that a template project should build out of the box.

**Comment by denolfe** [comment]
The blank template work fine with pnpm as demonstrated here:

<img width="840" alt="CleanShot 2023-11-08 at 21 37 43" src="https://github.com/payloadcms/payload/assets/65888/10b8bd98-a6dc-4634-a0e2-d4893b5f0962">

This issue is about being able to reference a dependency's dependency without causing an error. I would never expect to be able to reference `react` unless it is installed explicitly. `npm` just happens to allow this ability.
