### ISSUE TITLE
user.collection is missing on user object in admin.hidden

### ISSUE THREAD

**Issue by felskov** [payloadcms/payload#3974]
### Describe the Bug

I'm trying to create a collection for Photographers, which will allow my client to create a set of photographer accounts that can sign in to the admin interface with access to a limited set of features. I'm now trying to hide tabs in the navigation for collections and globals that the user doesn't have access to - which I'm trying to do as such:

export const Pages: CollectionConfig = {
  // ...
  admin: {
    // ...
    hidden: ({ user }) => {
      // only admin users are allowed to access pages
      return user.collection !== "admins";
    },
  },

While this should work according to TypeScript (collection is a property on the User auth object), it doesn't work in practice, because the user object does not include collection in the frontend (when I console.log(user); there is no collection property).

### To Reproduce

1. Login from a non-admin user collection
2. Try to log user.collection in admin.hidden callback (it's undefined)

### Payload Version

2.0.14

**Comment by DanRibbens** [comment]
Hey @felskov, 

It may be that the type is in incorrect and this could be considered a bug but there is another problem with what you're trying to do even if this were addressed. 

Currently the admin UI only works with a single auth collection since that is what the admin login form submits to. Unless you've figured out your own way to build multiple admin bundles your `user.collection !== "admins"` will always be falsey.

Instead what you could instead is have a single `users` collection and add an isAdmin checkbox field or roles as a select or relationship field.

Like I said, I'd be up for adding Omit<User, 'collection> to fix the type issue on the frontend but without a way for multiple different auth collections to access the admin UI, this isn't going to help you much.

**Comment by DanRibbens** [comment]
Feel free to reopen if there is something I've missed.

**Comment by felskov** [comment]
@DanRibbens Thanks for your feedback.

I did indeed hack my way around allowing multiple collections to sign in. That's another thing I wanted to address, but as it wasn't a bug I didn't feel like doing so right now :) 

My solution was to add a custom Login view that allows overriding `config.admin.slug`, which seems to work perfectly fine for our use case (a photographer logs in briefly, creates a gallery and uploads photos to it). I'm sure there are drawbacks to this approach and I know it's not officially supported - but the fact that it was so easy, leads me to wonder *why* it is only possible for one collection to sign into the admin panel.

However, I find it strange that only one collection can be configured for Login, while you allow definition of access control for the admin panel on a per-auth-collection basis. So I can indeed configure both an `Admins` and a  `Photographers` collection with access to the admin panel. The only thing that prevents me from doing so in practice is the fact that `config.admin.slug` can only point to one of them. Seems like a simple feature to allow multi admin-collections to sign into the admin panel:)

For what it's worth, I also did solve this issue with another small 'hack' by checking the domain of the user e-mail (if it matches my clients domain, I know it's an admin user) - so I'm good.

Let me know if you think it's worth raising a feature suggestion for supporting admin signin from multiple collections. Then I'll try to create a ticket that describes what I would like to achieve more specifically :)
