### ISSUE TITLE
Lexical BlockFeature: minRows/maxRows fails validation

### ISSUE THREAD

**Issue by pooledge** [payloadcms/payload#4000]
### Describe the Bug

I have Block which allows editors to create a multi-column layout. It consists of a Select and **three** conditional fields being an Array with `minRows` and `maxRows` corresponding to a selected option.

Having this Block outside Lexical works just fine. Now if otherwise: condition works perfectly in order to show or hide an Array UI component: Add/Remove buttons are properly updated as I change the layout. However as soon as I invoke validation, it fails as if there would be only one Array field with no conditions, i.e. having properly set up 2 rows fails with an error caused by a `minRows: 3`, or 4 rows — by `maxRows: 2` etc. It also breaks validation of the same Block outside Lexical at the same time.

### To Reproduce

Block fields:
```
fields: [
	{
		label: 'Layout',
		name: 'layout',
		type: 'select',
		options: [
			'1/1',
			'1/2',
			'2/1',
			'1/1/1',
			'2/1/1',
			'1/2/1',
			'1/1/2',
			'1/1/1/1',
		],
		defaultValue: '1/1',
		required: true,
	},
	{
		...BlockColumns,
		admin: {
			condition: (data, siblingData) =>
				['1/1', '1/2', '2/1'].includes(siblingData.layout),
		},
		minRows: 2,
		maxRows: 2,
	},
	{
		...BlockColumns,
		admin: {
			condition: (data, siblingData) =>
				['1/1/1', '2/1/1', '1/2/1', '1/1/2'].includes(
					siblingData.layout
				),
		},
		minRows: 3,
		maxRows: 3,
	},
	{
		...BlockColumns,
		admin: {
			condition: (data, siblingData) => 
				['1/1/1/1'].includes(
					siblingData.layout
				),
		},
		minRows: 4,
		maxRows: 4,
	}
]
```

Where `BlockColumns` in an array:
```
export const BlockColumns: ArrayField = {
	type: 'array',
	name: 'columns',
	interfaceName: 'BlockColumns',
	label: 'Spalten',
	labels: { singular: 'Spalte', plural: 'Spalten' },
	admin: {
		initCollapsed: true,
	},
	fields: [...],
};
```

### Payload Version

2.0.14

### Adapters and Plugins

richtext-lexical, db-mongodb, bundler-webpack

**Comment by AlessioGr** [comment]
Hey @pooledge just a heads-up:

You're using multiple fields with an identical name. Because this has a lot of negative side-effects (despite _kinda_ working here), this will not work in a future version and will cause an error to be thrown in the config sanitization process.

You could use a custom validate function, but that would not cause the number of columns to change in the admin UI. For that, you could use a custom React component.

The optimal way to handle this in the future would be for the `minRows` and `maxRows` properties to accept a function - that way, they could be conditional depending on the layout field's value. A PR for that is definitely accepted, if you'd like to prepare for the future version! Otherwise, feel free to make a feature request for this in GH Discussions :)
