### ISSUE TITLE
Cannot create custom component due to module loading issues (failing to load useField)

### ISSUE THREAD

**Issue by oranoran** [payloadcms/payload#416]
# Bug Report

I need to import a lot of markdown content from an old CMS into Payload.

After failing miserably to get it converted into SlateJS format, I figured I could just write an alternative rich-text component that uses Markdown directly. I'm doing this by wrapping [rich-markdown-editor](https://github.com/outline/rich-markdown-editor). See gist of the component [here](https://gist.github.com/oranoran/4baf37f53fb4ebbf7f437423a3b82441). Note that building this requires adding 2 modules - `rich-markdown-editor` and its peer dependency `styled-components`.

When I run `yarn dev`, I now get the following error:

      /myprojdir/node_modules/payload/components/forms.ts:1
      export {
      ^^^^^^
    
    SyntaxError: Unexpected token 'export'
        at wrapSafe (internal/modules/cjs/loader.js:1001:16)
        at Module._compile (internal/modules/cjs/loader.js:1049:27)
        at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

Strangely, I'm able to work around this when developing, by commenting out the entire component code, and restoring it only after `yarn dev` has started the dev server. But this is not a stable solution, plus a kinda similar failure happens also if I run `yarn build` and then `yarn serve`:

    internal/modules/cjs/loader.js:905
      throw err;
      ^
    
    Error: Cannot find module 'payload/components/forms'
    Require stack:
    - /myproj/dist/custom-components/markdown.js
    - /myproj/dist/collections/mycollection.js
    - /myproj/dist/payload.config.js
    - /myproj/cms/dist/changes-api/changes-controller.js
    - /myproj/cms/dist/server.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
        at Function.Module._load (internal/modules/cjs/loader.js:746:27)
        at Module.require (internal/modules/cjs/loader.js:974:19)
        at require (internal/modules/cjs/helpers.js:93:18)
        at Object.<anonymous> (/Users/myproj/dist/custom-components/markdown.js:38:15)
        at Module._compile (internal/modules/cjs/loader.js:1085:14)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
        at Module.load (internal/modules/cjs/loader.js:950:32)
        at Function.Module._load (internal/modules/cjs/loader.js:790:12)
        at Module.require (internal/modules/cjs/loader.js:974:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/myproj/dist/custom-components/markdown.js',

## Steps to Reproduce

1. `yarn install rich-markdown-editor styled-components`
2. Copy MarkdownField.ts from the [gist](https://gist.github.com/oranoran/4baf37f53fb4ebbf7f437423a3b82441) and create a text component at `src/custom-components/markdown.js`
3. Have a field use this component through `admin: { components: { Field: MarkdownField } },`
3. Run `yarn dev`

## Detailed Description

* payload v0.14.0
* node v14.18.1
* typescript 4.5.2
* Full package.json and tsconfig.json are also in the gist

**Comment by jmikrut** [comment]
Hey @oranoran — my team and I just created a brand new TypeScript project and everything worked as expected with your exact files. Note though that you suggest to name your file `markdown.js` and it includes TypeScript. That file NEEDS to have the `.tsx` extension because it is TypeScript and also includes JSX.

Is that possibly the issue? Either that or maybe `rm -rf ./node-modules` and re-yarn?

**Comment by oranoran** [comment]
Nope, that was just a mistake in reporting, the file is actually `markdown.tsx`

I tried removing node_modules and even yarn.lock, nothing helped

**Comment by jmikrut** [comment]
Hmmmm. OK. Here's a repo I made that attempts to reconcile this issue:

https://github.com/payloadcms/issue-416

If you pull this down and get it up and running, do you still show the issue?

It works great for me!

**Comment by jmikrut** [comment]
One other note:

The error that we're seeing is because for some reason your Node environment is **_not allowing_** Babel to transpile the contents of `/myprojdir/node_modules/payload/components/forms.ts` which is a TypeScript ESmodule.

By default, Payload handles the Babel setup for all files that are required or imported through the Payload config for you. [Here is our Babel config](https://github.com/payloadcms/payload/blob/master/src/babel.config.js). 

Do you have a custom Babel config?

**Comment by oranoran** [comment]
I was also unable to reproduce this with a clean repo.
Unfortunately we don't have a custom Babel configuration.
Maybe this gets affected by Babel configuration of some dependencies? But you did use my entire set of dependencies...

**Comment by oranoran** [comment]
Ok, I have a good lead on this!
Will update later today

**Comment by oranoran** [comment]
Ok, I created a minimal reproduction of the issue as a [PR](https://github.com/payloadcms/issue-416/pulls) on the issue-416 repo.

The root cause is that I imported a string with the server URL from `payload.config.ts` into `server.ts`.

This was all working fine, up until the time when I started to use useField, at which Babel decided to fall apart.

I'm not sure I understand the exact build flow of Payload, and how this import changes the behavior of Babel.
But if it's not allowed to use `payload.config.ts` in server code, this could be clearer from a naming / code structure perspective, as well as the documentation. Maybe it can even be checked somehow to fail earlier in a more informative way.

**Comment by jmikrut** [comment]
OK - I see the issue and understand why it's happening now!

The Payload config is loaded internally by Payload via [this file](https://github.com/payloadcms/payload/blob/master/src/config/load.ts).

You can see that `@babel/register` is used to load the config, utilizing Payload's own Babel config. This means that everything from the Payload config onward will be run through Babel.

But, the `server.ts` file in the demo repo is NOT run through `@babel/register`. Instead, `server.ts` is using _only_ `ts-node` to transpile. 

As a result, by loading the Payload config directly into `server.ts`, `ts-node` will trip up if your config has any code present that Babel would normally transpile (custom React components, etc). Payload tries to ensure that anything you do with your Express server is up to you, and not up to Payload.

Payload does export its internally used Babel config though which can be re-used.

To solve for the problems in your PR, we could use Babel to transpile the full `server.ts` itself, using the same Babel config. Maybe we will update `create-payload-app` to do this by default instead of `ts-node`.

Does this all make sense?

**Comment by jmikrut** [comment]
I agree. I would say the best pattern here is to try _**not**_ to import the entire Payload config into a server, because of the fact that it potentially comes with JSX.

Instead, you could "hoist" any values shared between server and Payload config to separate files that are written in plain CommonJS - i.e. your `serverURL` could be hosted in a file that's just....

```js
const serverURL = 'http://localhost:3000`;

module.exports = serverURL;
```

Then you could import these shared values in both your Payload config and your server.

Alternatively, we could export a pattern (which would be convoluted IMO) to be able to `loadConfig` into your server, thereby still taking advantage of Payload's built-in `@babel/register`.

What do you think?

**Comment by oranoran** [comment]
I'm ok with just duplicating the one line that I need... and the hoisting thing works too.

As far as I concerned you can close this issue, but I would just consider adding to the documentation a note saying you shouldn't import `payload.config.ts` (and anything else you think is relevant) into the server.

**Comment by jmikrut** [comment]
Hey @oranoran — 

Just updated the docs with some notes regarding this issue. I'm going to close it now. 

Thank you!
