### ISSUE TITLE
Deleting media will report an error

### ISSUE THREAD

**Issue by zhounewz** [payloadcms/payload#4242]
### Link to reproduction

https://payloadcms.com/

### Describe the Bug

<img width="1594" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/ed519829-a3eb-4e00-b03f-b1924fe1485a">
<img width="945" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/1ab76ded-b79a-43e2-affd-d56cd7534ef0">

### To Reproduce

"payload": "1.11.1",
"payload-s3-upload": "2.1.0",

### Payload Version

1.11.1

**Comment by DanRibbens** [comment]
payload-s3-upload is a community developed plugin. Since that isn't one we maintain I recommend using `@payloadcms/plugin-cloud-storge` and configuring it for S3 instead. It looks like there may be issues with delete in that package https://github.com/jeanbmar/payload-s3-upload/issues/19.

Also, version 1.11.1 of Payoad is quite old. I recommend updating that also.

I'm going to close this issue since I don't think it is a problem with Payload itself. Let us know if you need anything else.

Thanks!

**Comment by blueMountain007** [comment]
@DanRibbens  The documentation of plugin-cloud([link](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud)) is too simple. After reading it, I still don’t know how to use @payloadcms/plugin-cloud to reconstruct the previous code (see below). 

[plugin-cloud doc link](https://github.com/payloadcms/payload/tree/main/packages/plugin-cloud)
<img width="1262" alt="image" src="https://github.com/payloadcms/payload/assets/16400882/4eb2dc4f-0788-4217-bc4a-5c6ea8f9d6d0">


### previous code
payload version: 1.11.1
payload-s3-upload: 2.1.0

```
// Media collection
export const Media: MediaConfig = {
  slug: 'media',
  upload: {
    staticURL: '/assets',
    staticDir: 'assets',
    disableLocalStorage: true,
    s3: {
      bucket: environment.aws.s3UploadsBucket,
      prefix: `payload-cms/collections/media`,
      commandInput: {
        // optionally, use here any valid PutObjectCommandInput property
        // https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/interfaces/putobjectcommandinput.html
        ACL: 'public-read',
      },
    }
  },
}
```


payload.config.ts
```
import s3Upload from 'payload-s3-upload';

export default buildConfig({
  plugins: [s3Upload()],
  // rest of config
})
```
