### ISSUE TITLE
List table does not allow horizontal scrolling when loading Tailwind CSS

### ISSUE THREAD

**Issue by tyteen4a03** [payloadcms/payload#4262]
### Describe the Bug

The List view does not allow horizontal scrolling except in small breakpoint. This breaks tables with a lot of fields, as overflowed fields can't be made visible.

### To Reproduce

Create a collection with 10 - 20 fields, create a document, and try to view the document in List view with all 20 fields selected.

### Payload Version

2.1.1

**Comment by jacobsfletch** [comment]
Following up here, the issue stems from interfering Tailwind classes, described here: https://github.com/payloadcms/payload/pull/4275#issuecomment-1834194700

**Comment by jacobsfletch** [comment]
@tyteen4a03 which classes were interfering here? Just in case others stumble upon this issue. Wondering if there's anything we can do here to fix this as I'm sure many others will also want to load Tailwind.

**Comment by tyteen4a03** [comment]
> @tyteen4a03 which classes were interfering here? Just in case others stumble upon this issue. Wondering if there's anything we can do here to fix this as I'm sure many others will also want to load Tailwind.

The `table` class from Tailwind sets `display: table;` which breaks the scroll as the table is set to `display: block;`.

**Comment by jacobsfletch** [comment]
@tyteen4a03 the way forward here is to [prefix your Tailwind stylesheet](https://tailwindcss.com/docs/configuration#prefix), that way no CSS classes conflict. Payload uses global class names (as opposed to something like CSS Modules) so that you [can easily override or customize the CSS with your own stylesheets](https://payloadcms.com/docs/admin/customizing-css). Changing this one class would likely be considered a breaking change for this reason, but also there are dozens of other classes that could potentially overlap over time. Tailwind might also provide other means of solving this.
