### ISSUE TITLE
(Live-preview) Tabs are not traversed for relationships

### ISSUE THREAD

**Issue by matthijs166** [payloadcms/payload#4304]
### Describe the Bug

When logging here, the type is named **tab**
```js
console.log(fieldSchema.type)
```
https://github.com/payloadcms/payload/blob/4cfe4736273551e5c51431598054c09bd0e903f8/packages/live-preview/src/traverseFields.ts#L24-L27

Only the switch case handels the name **tabs**
https://github.com/payloadcms/payload/blob/4cfe4736273551e5c51431598054c09bd0e903f8/packages/live-preview/src/traverseFields.ts#L105-L110

Seems to me like a typo.
For now I fixed it by editing the switch case but I think that the live preview does not give the correct type name.

### To Reproduce

1. Create a collection with a field and set the type to tab
2. Create new tabs in the field
3. Set in one of the tab a relation to media
4. Open de live preview and the relation ship is not fetched

### Payload Version

2.2.2

### Adapters and Plugins

"@payloadcms/live-preview": "^0.1.6"

**Comment by jacobsfletch** [comment]
Heyyy @matthijs166 thank you as always for the details 

> When logging here, the type is named tab...seems to me like a typo.

Hmmm `tabs` appears to be using the correct the value in the switch, which is derived from here: 

https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/forms/field-types/index.tsx#L46-L47 via https://github.com/payloadcms/payload/blob/main/packages/payload/src/utilities/fieldSchemaToJSON.ts#L11-L12.

The issue seems to come from here: https://github.com/payloadcms/payload/blob/main/packages/payload/src/utilities/fieldSchemaToJSON.ts#L77 where we (incorrectly) set the type to `tab` instead of `tabs`. This would also explain why your temporary patch works. You're forcing the switch case to hit the incorrectly set key.

Thank you for point this out 👍 I will push a fix for this shortly along with a test to prevent regression.

**Comment by jacobsfletch** [comment]
Also how did you get those multi-code code references?! I tried but failed. Yours look so good.
