### ISSUE TITLE
collection resource not found in afterChange hook

### ISSUE THREAD

**Issue by calvinl** [payloadcms/payload#4686]
### Describe the Bug

See this discord message from another user which went unanswered: https://discord.com/channels/967097582721572934/1171779245954060298/1171779245954060298

I came across this yesterday when upgrading from Payload 1.x to 2.x. In 1.x, calling `payload.findByID` using `args.doc.id` would result in the document being returned. In Payload 2.x, this throws a not found error. This is confusing since the documentation states that the afterChange hook is called _after_ the resource is created or updated. However, it appears that the resource is not actually created until after the hook runs. Checking mongodb shows that the resource is not in the database at all when the not found error is thrown. 

However, if I don't call findByID and just return true or some value, the resource is created, which leads me to believe that there is a possible bug here where the resource isn't actually persisted to the database yet when the hook is called. 

### To Reproduce

1. Add an afterChange hook to a collection
2. In the hook, try and call `await req.payload.findByID({ collection: slug, id: args.doc.id })`. 
3. It will throw a not found error. 

### Payload Version

2.5.0

### Adapters and Plugins

db-mongo, bundler-webpack

**Comment by jmikrut** [comment]
I just responded on the Discord thread you linked but here is the answer:

In Payload 2.0, we've added database transactions - which means that if you want to interact with documents that you've just recently created, then you need to interact on the same transaction otherwise the document won't have been created yet. 

At the very last step of a Payload operation, the transaction is committed - meaning that's the point where the document actually gets saved to the DB.

This is an easy fix tho - all you have to do is make sure you pass either the req into any further local API operations, or the req.transactionID at the very least. 

Then the DB will know that the document that was just created was created within the transaction, and is not necessarily present in the DB itself yet. But everything will work as expected.

Does that make sense?

**Comment by calvinl** [comment]
That makes sense @jmikrut, thank you for the clarification. I was thinking it had something to do with transactions!

As a side question, do you guys plan on preparing migration guides for the next iterations of payload? I love Payload, but I've often found issues with upgrading versions because of undocumented changes or unexpected side effects. For example, I did not browse the transactions documentation but just now found that it directly mentions the afterChange hook on that page. However, the hooks page does not mention transactions at all -- that would've been helpful in debugging this issue.
