### ISSUE TITLE
Search plugin doesn't resolve docs

### ISSUE THREAD

**Issue by dkirchhof** [payloadcms/payload#4738]
### Describe the Bug

Hello,

I wanted to try out the search plugin, but it doesn't resolve the related docs. So I guess I'm not able to search anything.

Have a look:
![image](https://github.com/payloadcms/payload/assets/2778643/00b52280-bae5-49e3-b5f0-a78516e3c0aa)

### To Reproduce

Just use the search plugin with a basic config:

```ts
// ...
search({
  collections: [pages.slug],
}),
// ...
```

### Payload Version

2.6.0

### Adapters and Plugins

db-mongodb 1.1.0, plugin-search 1.0.1

**Comment by DanRibbens** [comment]
Can you provide more info about what you expect to happen?

The plugin deliberately has a `maxDepth: 0` set on the relationship field for the search collection. This is an optimization so that reading from the search collection does not blast your database with read requests. The expectation is that your interactions would be to first search for a document, then as a secondary action, the user would then pick one and you could fetch the actual document.

It sounds like instead of this you to have a maxDepth of 1 (or more) so that you can display the full document in a search result. This could be achieved if we make that property customizable by passing it to the search plugin config.

Would this solve your issue?

**Comment by dkirchhof** [comment]
Actually I may misunderstand the documentation since there is no example for the frontend.
I thought the creation / update of a document would save also some of the content of this document to the search collection. But it stores only the id, the title and eventually the _status field.

> The expectation is that your interactions would be to first search for a document

Means I can only search for these three fields?

So what is the value of this collection? Do I have to use the `beforeSync` option to add some more fields to this "search-doc"?

Anyways, I don't understand why I can't query the collection with a depth of something > 0 which should resolve the doc field since it is a relationship field?! Is it a bug?

If everything is fine with this plugin it would be helpful if the documentation will be improved:
1. Add an examples for "the other side".
2. Make clear what "search-critical" data means, where it comes from, if you have to save it by yourself or if the plugin does it for you automatically.

**Comment by jmikrut** [comment]
@dkirchhof basically you tell the plugin _**what fields you want to search on**_ by using the `beforeSync` function to create searchable documents that are built up and maintained over time. You don't just search across the entirety of the related documents - instead, you search explicitly on the newly maintained documents in your collection. So for example, the plugin includes a `title` search field, which you could then search on by saying something like `?where[title][like]=hello`. 

You can add more fields to the search index collection to search on multiple fields, you can combine multiple strings into the single `title` field, and lots more. But in any case, you're not searching on the related docs. Just searching on the data stored directly on the search index.

This is really mainly useful if you need to search across multiple different collections (`pages`, `posts`, `people`, etc.) at once. You don't need to use this plugin at all if you're just searching `pages` like you referenced.  In your case, if you're just searching `pages`, then you should just do `/api/pages?where[title][equals]=whatever`. That's effectively the same thing.

Does that make sense?

Note, like Dan said, we do have `maxDepth: 0` applied for performance reasons because most of the time for search you want it to be fast, to react to user input. No need to populate related documents most of the time.

**Comment by dkirchhof** [comment]
Got it. Thought that max depth is just the default but you can override it.
Thanks for clarification :)
