### ISSUE TITLE
plugin-cloud-storage: Ensure vite bundler compatibility

### ISSUE THREAD

**Issue by denolfe** [payloadcms/payload#4844]
[Discord Thread](https://discord.com/channels/967097582721572934/1162376403317182557)

Reports of the adapter returning an empty object when using the vite bundler.

v1.1.1

**Comment by linobino1** [comment]
+1

**Comment by AlessioGr** [comment]
This issue has been fixed in 3.0. Previously, plugin-cloud-storage was using webpack aliases in order to ensure server-only functionality does not make it to the client. This was likely not properly handled for vite.

In 3.0 we have decided to rely on next.js to handle the server-client boundary, and we have completely dropped support for our vite (and webpack) bundler. The best course of action here would be to upgrade to 3.0
