### ISSUE TITLE
richtext-slate: the link element does not store url

### ISSUE THREAD

**Issue by NataKosareva** [payloadcms/payload#4953]
### Describe the Bug

The richtext-slate link element with the type "inner": The earlier stored values are deleted after unpublishing and publishing the page.

### To Reproduce

1. Create any page with the richtext-slate
2. Add some content to the richtext  with link type "inner",  choose a document to link to (from page collection)
3. The link is stored in proper way
4. Unpublish the page and make some changes in richtext
5. Publish the page again
6. The link with type "inner" has no information of the linked page

### Payload Version

2.9.0

### Adapters and Plugins

payloadcms/richtext-slate: 1.4.0

**Comment by jmikrut** [comment]
Hey @NataKosareva — what is the `type: 'inner'` that you are referencing? 

Do you mean `type: 'reference'`?

**Comment by jmikrut** [comment]
Also - I just attempted to reproduce this and it works as expected when following your steps. To reopen this issue, we'll need a reproduction repo so that we can see what you are seeing.

If you would like us to take a look at your specific issue, hook us up with a reproduction repo following our CONTRIBUTING.md steps and we will see what we can do!
