### ISSUE TITLE
Bug in Admin Panel 

### ISSUE THREAD

**Issue by shaan22** [payloadcms/payload#4964]
### Describe the Bug

Experiencing an issue with the admin dashboard. When I try to open a collection, select an individual item, and click the edit button, I sometimes encounter an error. This happens across multiple collections, not just one.

![errorcart2](https://github.com/payloadcms/payload/assets/87020426/e2b754a8-f7e1-4e9f-8c46-060d246e3f7f)
![stripeproduct-err](https://github.com/payloadcms/payload/assets/87020426/f12d6f17-a8b5-474a-bb4b-5121f6d6bc4e)

### To Reproduce

this error  causes when we try to  change  the item from  collection through "Edit" button .

In User Collection  > Add cart Item  . 

Gives Type error    Uncaught (in promise) TypeError: getDocPreferences is not a function
    at index.js:409:35
    at step (index.js:1:83)
    at Object.next (index.js:1:83)
    at asyncGeneratorStep (index.js:1:83)
    at _next (index.js:1:83)
    at index.js:1:83
    at new Promise (<anonymous>)
    at index.js:1:83
    at index.js:434:5
    at index.js:135:15

### Payload Version

2.9.0

### Adapters and Plugins

db-mongodb, bundler-webpack

**Comment by denolfe** [comment]
I'm not able to recreate with the latest ecommerce template. Does this occur on a fresh database as well?

**Comment by SimYunSup** [comment]
`array`(items in Orders) or `blocks`(tabs in Pages) fields cause that Error. Because below code return null.

https://github.com/payloadcms/payload/blob/b392d656fe4d52f04cf88d9003a396b2e03b5ec7/packages/payload/src/admin/components/forms/field-types/Array/index.tsx#L53

https://github.com/payloadcms/payload/blob/b392d656fe4d52f04cf88d9003a396b2e03b5ec7/packages/payload/src/admin/components/forms/field-types/Blocks/index.tsx#L55

I think [EditMany](https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/elements/EditMany/index.tsx) component is not wrapped by `DocumentInfoProvider`.

**Comment by akshaj65** [comment]
when stripe is not created/linked . Editing the <b>"Stripe Product"</b> above causes an error .
