### ISSUE TITLE
Toast is not shown after successfully reset password

### ISSUE THREAD

**Issue by ps-amaureder** [payloadcms/payload#5099]
### Describe the Bug

After a user successfully changes the password no toast is shown. In the code below it looks like there should be a success toast, but it it not shown.

https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/views/ResetPassword/index.tsx
`const ResetPassword: React.FC = () => {
  const config = useConfig()
  const {
    admin: { logoutRoute, user: userSlug },
    routes: { admin, api },
    serverURL,
  } = config
  const { token } = useParams<{ token?: string }>()
  const history = useHistory()
  const { fetchFullUser, user } = useAuth()
  const { t } = useTranslation('authentication')

  const onSuccess = async (data) => {
    if (data.token) {
      await fetchFullUser()
      history.push(`${admin}`)
    } else {
      history.push(`${admin}/login`)
      toast.success(t('general:updatedSuccessfully'), { autoClose: 3000 })
    }
  }
`

### To Reproduce

- Click on the reset password link from the email
- Enter the new password twice
- Click the 'Reset Password' Button

### Payload Version

2.0.0

**Comment by fr3fou** [comment]
pAlso worth mentioning that if you use the same collection for your Admins and normal Users, you'll be greeted with this (unfriendly) message once you reset your password:
 
![image](https://github.com/payloadcms/payload/assets/1344906/d5b03726-aef5-403a-9dc2-f97e66e72931)

It'd be nice if:
1. You can set a `redirect` query param that can lead the user to some other page once you've reset your password
2. Be able to provide which collection the token is for – this would allow you to use 2 separate collections, one for admins and one for regular users. Currently, if you rely on the built in Admin panel for regular users to reset their passwords, Payload tries querying the Admin collection:
https://github.com/payloadcms/payload/blob/main/packages/payload/src/admin/components/views/ResetPassword/index.tsx#L23
This might not be the desired behavior, as you might want to reuse the built-in reset password page instead of making your own but you want to use another collection that's unrelated to the admin panel

**Comment by AlessioGr** [comment]
I have tested this in 3.0.0-beta.47 and the issue is resolved there!
