### ISSUE TITLE
Naming of enums inside of blocks with group fields (Postgres)

### ISSUE THREAD

**Issue by rfdomingues98** [payloadcms/payload#5123]
### Link to reproduction

https://github.com/payloadcms/payload/tree/f9a1781473f236ba541cc9c7226fcb8b7f7ecbc4/test/_community

### Describe the Bug

If you want to create a block, which contains two fields with the same name, where one of these is inside of a group, the group name will be ignored when generating the enum on the database, making the names for the enums on both fields overlap, resulting on the loss of the enum that comes first on the fields array.

Its easier to test it on the reproduction link I provide, but here is an example:
![image](https://github.com/payloadcms/payload/assets/34690999/d3309d14-eb68-4030-a7cd-2e61b4fa0061)
According to the code above, the postgres adapter should generate 2 enums: one for the `select` field and one for the `radio` field. Assuming that the collection in which this is occurring has the name `test` and the block field has the name `blocks`, the naming for both should be `enum_test_blocks_hero_type` and `enum_test_blocks_hero_link_type` respectively.

As displayed below, this is the only enum that was actually generated, and the values of the `radio` field are overriding the ones for the `select` field.
![image](https://github.com/payloadcms/payload/assets/34690999/909446fd-75b6-4bb3-a33a-9aff60e0d0dd)

This happened because the name of the `group` field was ignored while building the schemas for the database.

### To Reproduce

1. Create a collection with a `block` field
2. Create a block with two fields, whose values should be enumerable, in this case, `select` and `radio`
3. Add this block to the list of blocks available on the collection created in 1.
4. Ensure that both fields from 2. have the same name, and move one of them inside a `group` field
5. Try adding an entry
6. Notice that the values for the first enumerable field are invalid, since the expected values were the ones from the second field.

### Payload Version

2.11.1

### Adapters and Plugins

db-postgres

**Comment by DanRibbens** [comment]
I cannot reproduce this issue on the latest v3.

Here is a screenshot of the db object types that I have in the latest version using the config you provided for this issue.
![Image](https://github.com/user-attachments/assets/53a9fa29-7da5-4901-a080-f41e83f34735)

I imagine this is still broken in v2 because to fix it we'd also introduce a breaking change for existing projects with enums derived from fields in groups. My recommendation is to workaround this until you can upgrade v3 using the `enumName` property for the field config. You may want to use a function so that you can use the args that enumName gets to make each one unique.

Thanks for reporting.
