### ISSUE TITLE
Unable to login with accounts role=user at multi tenant example 

### ISSUE THREAD

**Issue by janybravo** [payloadcms/payload#5264]
### Describe the Bug

Logging as `user@abc.com` at http://abc.localhost.com:3003/admin displays message:

> Unauthorized, you must be logged in to make this request.
> 
> You are not allowed to access this page. 
>
> <Button>Log out</Button>

as `admin@abc.com` at http://abc.localhost.com:3000/admin/login seems to show dashboard correctly.

And thanks for all of your AMAZING work! 

### To Reproduce

1. Setup mongo docker container
2. cd to multi-tenant example code from `v2.11.2` tag. 
3. Run commands as instructed in README.md
4. Setup /etc/hosts with abc.localhost.com pointing to 127.0.0.1
5. Try to login with `demo@payloadcms.com` on localhost:3000 - all good.
6. Click Log out, Click log back in.
7. Try to login with `admin@abc.com` on abc.localhost.com:3000 - all good, access scoped well.
8. Click Log out, Click log back in.
9. Try to login with `user@abc.com` on abc.localhost.com:3000 - shows "Unauthroized" message.

### Payload Version

2.11.2

**Comment by cweseloh** [comment]
This is expected behavior, though the error message is confusing.  Non-admin users (like user@abc.com) should not be able to access the admin UI which is why there is an error message.  Logging-in with this account shows the message "Unauthorized, you must be logged in to make this request", however, this is misleading because the user is actually logged-in and calls to the API are successful (within the scope of their tenant permissions), it's just that they are not authorized to view the admin page.

**Comment by Djboy08** [comment]
Yeah the example does seem slightly confusing on what the use-case is for the ‘user’ role. As the demo is, its just for doing API calls pretty much. Not to access the GUI.
