### ISSUE TITLE
Collection hooks not fired when restoring document

### ISSUE THREAD

**Issue by siccifolium** [payloadcms/payload#5682]
### Describe the Bug

When I restore an older version of a document I would expect that the collection hooks are executed, for me this is not the case. If I have a collection with a `beforeChange` or `beforeOperation` hook none of them is called when I restore an older version of a document in that collection.

Going through the documentation about versioning and the other issues here it seems to me that this is not a bug rather than there is just no option to hook into  the process of restoring a version of a document. Is that correct?

If not what options do I have to execute code before a version is restored in order to block the user from restoring a specific version in case that this version contains data that is outdated.

### To Reproduce

Create a collection, add `beforeChange` or `beforeOperation` hooks with some logging output to be able to see when they are called. Create a document for that collection in the admin ui. Update that document a couple of times so that there are multiple versions of it. Open the versions history and restore one of the older versions.
`beforeChange` nor `beforeOperation` are called.

### Payload Version

2.8.2

**Comment by NiklasSchmidts** [comment]
Any news on this one?

**Comment by DanRibbens** [comment]
I think we should add `beforeOperation` and `afterOperation`. This should be done in v3 as it could be considered a breaking change. Having `beforeOperation` currently in your project you might not expect this code to run on restore, this could be an issue in some projects.

I'd also consider adding a `beforeRestore` as a new collection hook as an alternative to calling `beforeChange` and adding more variables to the arguments as that wouild force a lot of functions to be updated in existing projects to handle the additional calls.

For now you could work aroud this by adding your own custom endpoint to the collection so that you have the same method that then calls next. You won't be able to modify the data being updated within the restore like a normal hook would allow.

```
endpoints: [{
  'path': `/${collection.slug}/versions/:id`
  method: 'POST',
  handler: (req, res, next) => {
  // do whatever you want to be fore the operation
  // next()
}
}]
```
