### ISSUE TITLE
afterChange hook runs before data is persisted to the database ?

### ISSUE THREAD

**Issue by Jonashr** [payloadcms/payload#5886]
### Link to reproduction

Private repo

### Describe the Bug

We have been trying to use NextJS [on-demand-revalidation](https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#on-demand-revalidation) for our Blog posts. To do this, we tried using the afterChange collection hook. 

But it seems like the in the afterChange hook the data is not persisted to the DB when the hook is called, so calling revalidate only makes the NextJS app re-fetch the blog post as it was before it was updated.

Let's say we have a blog post which is named Blog Post ABC, and we are trying to change to Blog Post ABCDEF. This is what happens:

- Collection afterChange hook starts running. 
- A revalidate request is sent to the NextJS application from the afterChange hook.
- NextJS application revalidates the blog post
- On revalidate, the NextJS application fetches the updated blog post from the database.

However, the blog post fetched by NextJS is still the old blog post that hasn't been updated.

To verify my suspicions I tried running a findById query in the hook:
```javascript
const blogById = await payload.findByID({
  collection: "blogPosts",
  id: doc.id,
  draft: true,
});

// Returns Blog Post ABC for the title, not Blog Post ABCDEF
```

In this case, the Blog Post is still named Blog Post ABC. I also tried adding a fetch in the revalidate function of the NextJS app, and the same still happens there, the old Blog Post is fetched.

Is this the intended behaviour of the afterChange hook ? If so what am I supposed to use for revalidating something on my NextJS app whenever data is created, updated or deleted ? There doesn't seem to be any other hooks that seem to fit the use case. I also tried the afterOperation hook but it seems the behaviour is exactly the same there.

### To Reproduce

- Create a new collection called **BlogPost**
- Set the title to _ABC_ and save.
- Now create a **afterChange** hook on the collection.
- Change title of Blog post title to _ABCDEF_
- In the afterChange hook, the document has updated its title to ABCDEF, however by fetching the BlogPost from payload, the Blog Post title is still ABC.

Ideally, you'd also have a frontend using NextJS + On-demand-isr that actually uses the revalidate function implemented something like this:

```javascript
export default async function handler(req, res) {
  // Check for secret to confirm this is a valid request
  if (req.query.secret !== process.env.MY_SECRET_TOKEN) {
    return res.status(401).json({ message: 'Invalid token' })
  }
 
  try {
    // this should be the actual path not a rewritten path
    // e.g. for "/blog/[slug]" this should be "/blog/post-1"
    await res.revalidate('/blog/id-from-payload')
    return res.json({ revalidated: true })
  } catch (err) {
    // If there was an error, Next.js will continue
    // to show the last successfully generated page
    return res.status(500).send('Error revalidating')
  }
}```

And then confirm that on the frontend, the blog post is not updated.

### Payload Version

2.12.1

### Adapters and Plugins

postgres

**Comment by DanRibbens** [comment]
Hey @Jonashr, 

Thanks for that info, this is helpful and very clear to me of what the issue is.

Due to transactions you aren't able to fetch the content change "ABCDEF" at the time of the afterChange hook.

In your hook you can pass the `req` which includes a transactionID and any payload local operation or payload.db operation that have the req will use it. In that way your payload.findByID example could work to get "ABCDEF". 

Thinking through the options here, you could disable transactions. If you are using mongoDB you'd do that with `transactionOptions: false`. Turning this off reduces your overall data integrity so errors that come up in normal operation might leave a bad state of data changes from one request.

Another option is to add a setTimeout() this isn't great because of course you won't really know how long to wait before knowing a transaction has completed and it is ugly. If an error occurs and revalidation occurs it shoudln't be a big deal since the content of the last validation will come up again on the next query after a rollback, so probably fine.

Ideally though we should have a pattern for this that would let you push callbacks after a commit. I want it to have a good DX of course, so I'm open to ideas.

**Comment by DanRibbens** [comment]
Hey @Jonashr,

Thanks for that info, this is helpful and very clear to me of what the issue is. I'll add some ideas on top of what James has already stated.

In your hook you can pass the `req` which includes a transactionID to any payload local API functions or payload.db operationsto use the same transactions. In that way your payload.findByID example could work to get "ABCDEF".

You could pass your data to the validation endpoint from this fetch if you wanted one workaround option.

Another option is to add a setTimeout() this isn't great because of course you won't really know how long to wait before knowing a transaction has completed and it is ugly. If an error occurs and revalidation occurs it shoudln't be a big deal since the content of the last validation will come up again on the next query after a rollback, so probably fine.

You could disable transactions as another option. If you are using mongoDB you'd do that with transactionOptions: false. Turning this off reduces your overall data integrity so errors that come up in normal operation might leave a bad state of data changes from one request. Not ideal, but still an option.

Ideally we should have a pattern for this that would let you push callbacks after a commit. I want it to have a good DX of course, so I'm open to ideas.

**Comment by Jonashr** [comment]
@jmikrut @DanRibbens Thanks for the great suggestion!  You were right about the transaction not being completed being the issue here. As suggested I added the code to commit the transaction:

```javascript
  const { payload, transactionID } = req

  await payload.db.commitTransaction(transactionID)
```

Once I committed the transaction it worked like a charm.  So I am just going to close this issue as it has been solved. Thanks again!

**Comment by felixmokross** [comment]
I just ran into this too. For me it was a quite confusing tbh, I did not expect the `afterChangeHook` to run before the changes are actually committed to the DB. After I read the source code, it made sense what was happening and your explanation confirms this.

Similarly to the op, in my use case I want to purge and prime a cache of an external app when the user has saved something in the CMS. The cache priming within the hook didn't work, as the external app would always pull the previous data from the CMS.

I understand that there may be other use cases where it is beneficial to have the transaction commit only after the hook has run. Your described solution with committing the transaction in the hook works for me well. I would appreciate a better API for this though (maybe an `afterCommitHook`)?
