### ISSUE TITLE
Missing empty optional fields in response after create

### ISSUE THREAD

**Issue by wojciechkrol** [payloadcms/payload#643]
# Bug Report

Optional fields are missing from response when are not present during create.

## Expected Behavior

When item is created and optional field is not present in payload then this field should be visible with `null` value.

## Current Behavior

When item is created and optional field is not present in payload then this field is not visible in response.

## Steps to Reproduce
1. Create collection with at least one not required field.
2. Create item with POST method and skip this field in payload.
3. Created item does not display this field.

## Detailed Description

```ts
const Clients: CollectionConfig = {
  slug: "clients",
  admin: {
    useAsTitle: "name",
  },
  fields: [
    {
      name: "name",
      type: "text",
      required: true,
    },
    {
      name: "description",
      type: "text",
    },
  ],
}
```
Create request:
```
POST http://localhost:3000/api/clients
{"name": "Foo"}
```
Response:
```
{
    "message": "Client successfully created.",
    "doc": {
        "name": "Foo"
    }
}

**Comment by DanRibbens** [comment]
Payload behavior for missing values being `undefined` instead of `null` is the way it is due to the underlying Mongo driver.

I think this is expected for any no-sql type database. If you wish to save or retrieve field values as `null` instead of `undefined`, you could consider adding afterRead or beforeChange hooks instead of undefined values if that is what you prefer from your API. I haven't tested what impacts that might have on the UI though so I can't say this is recommended.

I'm happy to discuss further or consider any documenation you can point me to if I'm missing something.
