### ISSUE TITLE
Showing blank screen

### ISSUE THREAD

**Issue by akanshSirohi** [payloadcms/payload#647]
# Bug Report

## Expected Behavior
Shows normal login screen while browsing `http://localhost:3000/admin`

## Current Behavior
Shows blank screen while browsing `http://localhost:3000/admin`

## Steps to reproduce
1. Install axios as a dependency.
2. Run payload cms.

## Detailed Description
It's just showing the blank screen, it was just working fine and I installed `axios` and the next moment it just broke and showed a blank screen. I have already reverted the changes and also tried to reinstall the payload dependency but nothing happening.

Also showing this error in CLI `[18:20:10] ERROR (payload): There was a problem setting up the mock email handler`

-> Console Errors
![Screenshot 2022-06-10 235929](https://user-images.githubusercontent.com/34837239/173128422-b40e7420-3855-40ac-aa66-5c0d2235c6c1.png)

-> Blank Screen
![Screenshot 2022-06-10 235958](https://user-images.githubusercontent.com/34837239/173128433-b5c54807-f023-4872-b67e-3b9911bfbaea.png)

Payload Version: 0.17.3
Browser: Firfox Developer Edition, Chrome
OS: Windows 11
Package Manager: npm v8.9.0

**Comment by DanRibbens** [comment]
Can you share your package dependencies + devDependencies?

This can happen when you have more than one react copy in `node_modules`.

**Comment by akanshSirohi** [comment]
@DanRibbens I just figured out what happened and updated my issue.

**Comment by akanshSirohi** [comment]
@DanRibbens If I am trying to install any other package, it is behaving the same. I tried to install a package `uniqid` and again it's gone.

**Comment by jmikrut** [comment]
Hey @akanshSirohi — 

At Payload and TRBL, we use `yarn` instead of `npm`, which automatically handles `legacy-peer-deps`.

Heroku doesn't seem to support `--legacy-peer-deps`, but they do allow you to use Yarn, which would be a potential fix.

Apparently Heroku will use `yarn` automatically if you have a `yarn.lock` file rather than a `package-lock.json` file. Here's a link from Heroku that speaks to this. That should solve your Heroku issue.

https://devcenter.heroku.com/changelog-items/1065

Should we close this issue at this point? Thank you for your investigation!

**Comment by akanshSirohi** [comment]
Thanks, @jmikrut for your review, I was working on Payload for so many days and faced issues but I also find it incredibly awesome to work with and already solved the Heroku problem with yarn. I hope Payload will improve and offer a lot more many features in further releases.
