### ISSUE TITLE
Warning from yarn install

### ISSUE THREAD

**Issue by wrobson-lllow** [payloadcms/payload#6492]
### Describe the Bug

I was originally on payload 2.5.0 and when running a yarn install I got an error for the following dependencies of payload:

payload > json-schema-to-typescript > glob > inflight@1.0.6
payload > pino-pretty > help-me > glob > inflight@1.0.6

The error is:
This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.

I updated Payload to version 2.18.3, as well as updating all of my payload plugins to the latest version and I'm still receiving the error.

### To Reproduce

Run Yarn install on payload v2.18.3

### Payload Version

2.18.3

### Adapters and Plugins

 "@payloadcms/bundler-webpack": "^1.0.6",     "@payloadcms/db-mongodb": "1.5.1",     "@payloadcms/plugin-cloud": "^3.0.1",     "@payloadcms/richtext-slate": "^1.5.2"

**Comment by MarkAtOmniux** [comment]
https://www.npmjs.com/package/inflight

Looks like inflight is deprecated.  According to this SO post, it is caused by something in eslint-typescript because there is a version mismatch;

https://stackoverflow.com/questions/78527247/have-used-npm-create-vitelatest-but-after-finishing-the-compilations-am-getting
