### ISSUE TITLE
Lexical Editor's Internal Link includes the whole referenced document, making requests super heavy

### ISSUE THREAD

**Issue by tomperalta** [payloadcms/payload#6547]
### Describe the Bug

I'm using Lexical editor on my Payload CMS instance. After seeing a bunch of issues while trying to build a NextJS site connected to my CMS instance, **I noticed the build requests went from ~300 kb to 10-20 MB (!!!), causing timeouts and `504` errors**. 

After some more inspection, I saw that **the objects from the `Rich Text` fields using Lexical editor that included `Internal Links` contained the whole deep-populated-document that these links were referencing to**.

I don't know if this is intended or not, but including the whole document the link is referencing to seems like it will bloat and eventually break every request to the document that contains that field.

### To Reproduce

- Install Payload CMS.
- Create a `Rich Text` field that uses Lexical Editor.
- Inside the `Rich Text` field, add a link of type `Internal Link` and point it to a document inside your CMS.
- Inspect the entry's API to see the whole deep-populated-reference to the document.

### Payload Version

2.0.0

<img width="572" alt="Screenshot 2024-05-29 at 10 35 35" src="https://github.com/payloadcms/payload/assets/57907757/72ebd150-7661-450e-a0d1-2fe2ad1a8aa3">

**Comment by AlessioGr** [comment]
Hey, this is completely intended that way. Internal links are just like relationships, pointing to another document, and should populate like them.

If you would like to disable this behavior, you can set `maxDepth` to `0`, which is a property on the `LinkFeature`. Alternatively, you can set maxDepth to 0 for the entire richText field, which means it would also apply to population of relationships and uploads

**Comment by HriBB** [comment]
@AlessioGr is there any way to control the return value?

**Comment by AlessioGr** [comment]
yep, you can replace the link internal link field with your own

**Comment by HriBB** [comment]
@AlessioGr do you meanreplace the entire `LinkFeature`? But then I would also have to replace `RelationshipFeature` and `UploadFeature`, because they also return full objects. I would like to omit most of the fields from Link|Relationship|Upload and only keep two or three fields that I need. For Upload I need image URL, for Relationship and Linkfor example I need a Post.slug and Post.category.slug to render the correct URL.

Did some debugging ... there's a lot to take in :sweat_smile: but I believe if I had "access" to [this line of code](https://github.com/payloadcms/payload/blob/main/packages/richtext-lexical/src/populate/populate.ts#L53), I could omit fields from the `doc` based on type. Right?

Anyhow ... would be cool, if we could control Link|Relationship|Upload return value through payload config. Tried to use `afterRead` on collection and field level, but seems that `richText` is [resolved differently](https://github.com/payloadcms/payload/blob/main/packages/payload/src/graphql/schema/buildObjectType.ts#L482).
