### ISSUE TITLE
SVG favicon not supported by Safari

### ISSUE THREAD

**Issue by franciscolourenco** [payloadcms/payload#6905]
### Describe the Bug

<img width="1344" alt="image" src="https://github.com/payloadcms/payload/assets/208149/0f969844-9575-445a-a8bb-3114a9169dcd">

https://caniuse.com/link-icon-svg

### To Reproduce

1. Open Payload in Safari (demo seems to work, but maybe because it's hosted at payloadcms.com)

### Payload Version

2.22.0

**Comment by jacobsfletch** [comment]
@franciscolourenco the demo likely displays a _fallback_ favicon that the browser has cached on the top-level domain (payloadcms.com). That site has a `favicon.ico` hosted on the root of the application: https://github.com/payloadcms/website/blob/main/public/favicon.ico. Unsupported browsers will use this when no valid favicon was found, including sub-domains, it seems. But adding this to the Payload Admin Panel in not an option, however, because favicons need to be 100% configurable through the Payload Config. A static file would fall outside of this capability. 

BUT in 3.0, we've actually moved to PNG favicons, so this is no longer an issue. For this reason I'm going to go ahead and close this ticket. For 2.0, Safari would either need to increase support to SVG favicons, or you'd have to find another way to inject a `favicon.ico` into the root of your application (not sure if this is even possible, so if anyone has ideas, feel free to leave a comment).

**Comment by jacobsfletch** [comment]
I suppose it's _possible_ for us to extend the favicon config a bit, which would allow you to supply your own `.ico` file. But this wold require an additional set of logic in order to check the file type in order to properly set the `type` attribute in the DOM. Instead of retrofitting support for this, we strongly recommend upgrading to 3.0 if this is an option for you, as that the the more permanent fix going forward.

**Comment by franciscolourenco** [comment]
v3.0 is good enough, this is not that important 👍
