### ISSUE TITLE
Live Preview: Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by robinscholz** [payloadcms/payload#7164]
### Payload Version

3.0.0-canary.6de2b29

### Node Version

20.15.1

### Next.js Version

15.0.0-rc.0

### Describe the Bug

``` console
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:3000') does not match the recipient window's origin ('http://localhost:3030').
```

``` console
[Error] Unable to post message to http://localhost:3000. Recipient has origin http://localhost:3030.
 ```

Getting this warning (in Chrome) or this error (in Safari). The payload.config.ts has a cors value set:

``` ts
export default buildConfig({
  serverURL: process.env.PAYLOAD_SERVER_URL || 'http://localhost:3030',
  cors: [process.env.PAYLOAD_LIVE_PREVIEW_URL || 'http://localhost:3000'],
  …
 ```
 
 The live preview loads the iFrame correctly, but does not update at all. 

### Reproduction Steps

If necessary we can invite you to our monorepo!

**Comment by robinscholz** [comment]
It is worth noting, that we are using a custom endpoint to fetch data in our frontend, but it seems that the error/warning is unrelated.

**Comment by jacobsfletch** [comment]
@robinscholz it sounds to me like this is an issue related to your front-end implementation. In order to achieve cross-domain communication, the child window must open first and "call" back to the parent window _before_ it begins sending its messages down. Otherwise, this error is thrown. This is a security feature built directly into the `postMessage` API. I can add some troubleshooting docs based this discussion, once we can confirm this is the issue.

**Comment by jacobsfletch** [comment]
Closing for now, since this is likely an improper configuration and not an issue with core functionality. @robinscholz If you can show me what your front-end implementation looks like, I can try and help further. Feel free to keep the conversation in this issue going.
