### ISSUE TITLE
Upload by URL in file upload dialog causes CORS error if file is not on the same domain

### ISSUE THREAD

**Issue by genox** [payloadcms/payload#7208]
### Payload Version

beta.53

### Node Version

min by demo-3.0

### Next.js Version

min by demo-3.0

### Describe the Bug

When trying to upload a "foreign" file using the newly added upload by pasting an URL feature, I get a CORS error on deployments as well as on localhost.

- There should be either an option to define CORS rules for payload to use this feature, some guidance in the docs to make it work or have the server fetch the file directly (I think the latter would be my preferred way - no point downloading to the client and uploading again).
- Reconsider the wording of the button - currently says "Add image" - I would suggest to rename this to "Add file from URL" or something more generalised since images are just one type of files that can be added like this.

I am actually quite thrilled about this feature and would like to use it properly, will make a migration of content much easier that I am working on :)

### Reproduction Steps

Create a collection with some file field, paste an URL to a file on a different domain and hit "Add image", CORS error should pop up in lower right, check console.

**Comment by JarrodMFlesch** [comment]
@genox I think the error you are seeing is coming from the host you are requesting from, not from your application. i.e. if you attempt to paste this url: `https://images.unsplash.com/photo-1721069209947-418ebf9d09e8` you should be able to download/upload that image just fine as an example. So if you have access to that server, you would need to whitelist your domain there.

As for downloading via the server, we chose not to do anything like that since you may choose to disregard the file before uploading it.

I do agree with the "Add Image" comment though. @PatrikKozak we should revise this to be "Add File"

**Comment by genox** [comment]
@JarrodMFlesch True, it is a an issue on the remote end, some ancient PHP script that we do not have access to. 

I think it is fair to assume that issues regarding CORS will pop up over and over again, in real world scenarios, if the client is involved in downloading. One rather involved way to solve this is to allow setting a prefix, a proxy, essentially, to circumvent that. Then run some docker image that acts as a proxy.

Another way that could be bundled with payload would be to have a next api route that pipes the file thru to the client which then uploads it again if so desired. This prevents accumulation of temporary files or storage needs but still allows to use any kind of source, whether CORS is involved or not. This could be a generic solution that might offer some benefits in the future (importing or exporting data, etc).
