### ISSUE TITLE
Can not hide "Generate New API Key" button in "Users" Collection for specific users based on condition & requirement. 

### ISSUE THREAD

**Issue by RiteshMRI** [payloadcms/payload#7479]
### Payload Version

3.0.0-beta.68

### Node Version

v20.15.0

### Next.js Version

15.0.0-canary.53

### Describe the Bug

I can not hide "Generate New API Key" button in "Users" Collection for specific users based on condition & requirement. 

Based on some requirements, i want to hide  "Generate New API Key" button in "Users" Collection. But there is no any provision so that i can hide "Generate New API Key" button conditionally. 

### Reproduction Steps

1) Login into payload.
2) Navigate to users collection.
3) Click on any existing user from grid (users list) to open the user in edit mode.
4) Observe the screen 

I have attached the screenshot (as shows as below) related to this issue.

![Screenshot1](https://github.com/user-attachments/assets/195bd0ba-c518-4dae-aebf-d632530690aa)

**Comment by jmikrut** [comment]
Hey @paulpopus let's try and brainstorm what the best solution would be in order to hide the API key functionality. I know that you can pass in your own `apiKey` field, which should get merged with the Payload default `apiKey` field, which could take access control functions. We might be able to then use those access control functions to conditionally show / hide the UI.

But I'm not sure. Let's investigate!

**Comment by paulpopus** [comment]
We're fixing this up in this PR https://github.com/payloadcms/payload/pull/7591

Details in that PR but essentially after this is released, you can add this field to your auth collection

```ts
{
  name: 'apiKey',
  type: 'text',
  access: {
    update: ({ req }) => req.user.role === 'admin',
  }
}
```
