### ISSUE TITLE
Payload admin pannel production is so slow

### ISSUE THREAD

**Issue by in3learning** [payloadcms/payload#7493]
### Link to reproduction

https://in3learning-production-x87x.vercel.app/

### Payload Version

3.0.0-beta.71

### Node Version

"^18.20.2 || >=20.9.0"

### Next.js Version

15.0.0-canary.77

### Describe the Bug

I deploy this to vercel. The admin pannel is much faster in my localhost and really slow in production and i don't know why.

### Reproduction Steps

go to my reproduction link and login as default 

email: 'dev@payloadcms.com',
password: 'test',

you will see it is really slow 

### Adapters and Plugins

I am using vercel-postgres and vercel-blob-store

**Comment by jmikrut** [comment]
Hey @in3learning your reproduction no longer is reachable but this is likely due to Vercel cold starts. On free projects especially, you'll have to wait for your project to warm up and will, once in a while, always experience cold starts. I think on their paid plans they have measures to prevent against experiencing cold starts but it's just a side-effect of AWS Lambda / serverless functions in general. 

If you use a separate host like Render, Fly IO, or Payload Cloud, it will be fast just like localhost.
