### ISSUE TITLE
Cannot find module 'drizzle-orm' when exec payload migrate

### ISSUE THREAD

**Issue by smoothdvd** [payloadcms/payload#7526]
### Describe the Bug

After generate migrate script by run payload migrate:create
the code:
```
import { sql } from 'drizzle-orm'
```
script can't find drizzle-orm package because of peer dependency

### To Reproduce

with pnpm package manager:
1. pnpm payload migrate:create
2. pnpm build
3. error reported:
```
src/migrations/20240806_010523.ts:2:21 - error TS2307: Cannot find module 'drizzle-orm' or its corresponding type declarations.

2 import { sql } from 'drizzle-orm'
                      ~~~~~~~~~~~~~
```

### Payload Version

2.25.0

**Comment by r1tsuu** [comment]
Hey @smoothdvd, thank you for the report!

I can't reproduce it on both 2.0 and 3.0 fresh projects, using pnpm as well.
I can think that it could happen since it's a peer dependency, and package managers don't always install them.
In 3.0 we now have import directly from `@payloadcms/db-postgres`:
```ts
import { sql } from '@payloadcms/db-postgres'
```
 so this shouldn't be an issue anymore there.
