### ISSUE TITLE
Products not being pulled in from Stripe

### ISSUE THREAD

**Issue by grantspilsbury** [payloadcms/payload#7577]
### Link to reproduction

https://github.com/payloadcms/payload/tree/main/templates/ecommerce

### Describe the Bug

This is not a bug but didn't know where else to post it.

I have cloned `https://github.com/payloadcms/payload/tree/main/templates/ecommerce`, set up the 4 Stripe env vars
```
STRIPE_SECRET_KEY=sk_test_51P
PAYLOAD_PUBLIC_STRIPE_IS_TEST_KEY=true
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_51P
STRIPE_WEBHOOKS_SIGNING_SECRET=whsec_df
```

I have started the webhooks listener in new tab `yarn stripe:webhooks`.
I am seeing Stripe webhook events for the new products
```
2024-08-08 13:06:33   --> price.created [evt_1PlOYXKs5VDA]
2024-08-08 13:06:33  <--  [200] POST http://localhost:3000/stripe/webhooks [evt_1PlOYXKs5VDAk]
2024-08-08 13:06:33   --> product.updated [evt_1PlOYXKs5VDA]
2024-08-08 13:06:33  <--  [200] POST http://localhost:3000/stripe/webhooks [evt_1PlOYXKs5VDA]
```

### To Reproduce

When I try select a Stripe product, on the Product page, the "Stripe product" dropdown is empty and has "No options".

Is there an extra step I need to follow to get the Stripe products synced?

### Payload Version

2.25.0

**Comment by paulpopus** [comment]
Hey @grantspilsbury I just tested this functionality and it worked for me.

Out of the box we don't create Stripe products for you, since it ties into the checkout process we simply create a reference to the wanted products. Have you added any products in Stripe before trying to link them?

If so can you double check you're using the correct API key for the Stripe environment? If you're encountering issues beyond this I'm happy to take a look if you can provide a repo, otherwise I'll close this issue for now
