### ISSUE TITLE
The locale dropdown does not switch the locale

### ISSUE THREAD

**Issue by ivan-kardash** [payloadcms/payload#7604]
### Link to reproduction

https://github.com/ivan-kardash/payload/tree/locale-dropdown-not-switching

### Payload Version

3.0.0-beta.73

### Node Version

20.15.0

### Next.js Version

15.0.0-rc.0

### Describe the Bug

The locale dropdown does not switch the locale. It changes query string params only without any UI updates. I caught several times states, when selected in the dropdown locale, did not correspond with the locale that UI was rendered

### Reproduction Steps

1. Setup in payload config 
```ts
localization: {
    defaultLocale: 'en',
    locales: ['en', 'by'],
    fallback: true,
}
```
2. Create Global with fields that include filed with config like this
```ts
{ name: 'globalText', type: 'json', required: true, localized: true  }
``` 
3. Pass created early Global to payload config
4. Setup in payload config
```ts
  onInit: async (payload) => {
    await payload.updateGlobal({
      slug: "your_slug_here",
      locale: "en",
      data: {
        globalText: { someText: "Some global text in English" },
      },
    });
    await payload.updateGlobal({
      slug: "your_slug_here",
      locale: "by",
      data: {
        globalText: { someText: "Нейкий глабальный тэксту па-беларуску" },
      },
    });
  }
  ```
5. Log in
6. Forward to Global and try to switch locale

### Adapters and Plugins

db-postgres

**Comment by paulpopus** [comment]
Can you make sure you're on the following Next and React versions?

```
"react": "^19.0.0-rc-06d0b89e-20240801",
"react-dom": "^19.0.0-rc-06d0b89e-20240801",
"next": "15.0.0-canary.104",
```

The `rc` release from nextjs is quite old at this point and we're using canary.104 internally.

Does this still happen on these versions?

**Comment by paulpopus** [comment]
Closing this as far as my testing goes it works, but let me know if the above doesn't fix it for you

**Comment by ivankyrpa** [comment]
Hey @paulpopus! Thanks for your prompt reply and suggestion.

I've tried to create new `payloadcms` project utilizing `npx create-payload-app@beta` command and noticed that the issue still reproduced.

The issue is most likely in data displaying. It's tied at least with `json` localized fields in edit view since list view and REST api work as expected.

Attached a screen record with reproduction demo below.
The code could be found here: https://github.com/ivankyrpa/payload-beta-test

Packages versions:
```
  "payload": "3.0.0-beta.87",
  "react": "19.0.0-rc-06d0b89e-20240801",
  "react-dom": "19.0.0-rc-06d0b89e-20240801",
  "next": "15.0.0-canary.104"
```


https://github.com/user-attachments/assets/3779f81d-7230-49a4-a778-2943c8636d03



What are your thoughts? Probably we should reopen the issue and proceed investigation?

**Comment by paulpopus** [comment]
@ivankyrpa I'm now looking into our locale-related issues but on the latest beta it seems like I cannot reproduce this bug

Can you confirm it's working fine now?

**Comment by ivan-kardash** [comment]
I've checked on `3.0.0-beta.98` and it looks like it works correct
