### ISSUE TITLE
Some arguments type is missing in afterOperation hook

### ISSUE THREAD

**Issue by smoothdvd** [payloadcms/payload#7642]
### Payload Version

3.0.0-beta.77

### Node Version

20

### Next.js Version

15.0.0-canary.53

### Describe the Bug

Some arguments type is missing in afterOperation hook

### Reproduction Steps

```
export const afterOperation: CollectionAfterOperationHook = async ({
  args,
  operation,
  result,
  req,
}) => {
  if (operation === 'create') {
    const { url, download } = args.data
  }
}
```

(parameter) result: unknown
Property 'url' does not exist on type 'RequiredDataFromCollectionSlug<string>'

**Comment by paulpopus** [comment]
Hey @smoothdvd can you pass your collection slug into the type?
eg:
```
CollectionAfterOperationHook<'posts'>
```

Then your data there will be inferred correctly from the generated types. These should generate automatically but if not then `pnpm generate:types` or `pnpm payload generate:types` should do that for you.

Also please note that on the beta versions 77+ you should be on Next canary.104 as a minimum.

I tested the above in a fresh project, so let me know if this fixes your issues, otherwise please provide a reproduction so I can take a closer look!

**Comment by smoothdvd** [comment]
@paulpopus Thank you, it worked after I follow your instruct (I also upgraded to beta.79 and next 15.0.0-canary.104).
