### ISSUE TITLE
Rich Text Editor fails when pasting

### ISSUE THREAD

**Issue by Rheaparks** [payloadcms/payload#7653]
### Describe the Bug

This issue was previously [described here](https://payloadcms.com/community-help/discord/rich-text-editor-error-when-pasting-between-editors), but we've been able to reproduce it with a brand new payload 2 + Postgres installation.

Basically we have a field that fails as soon as we paste something inside. And then we cannot type inside the field. After reloading, we can write but we cannot delete anything. It just fails.
It's unclear what caused the fields to fail. It started out well, we've been able to edit a few fields and then it broke up.

How are we supposed to fix this in our current database? Ideally without losing our data, but we're open minded.

here are the error messages we've received in the Chrome Dev Tools :

```
Cannot get the start point in the node at path [] because it has no start text node.
Cannot read properties of undefined (reading 'children')
Cannot resolve a Slate point from DOM point: [object Text],0
Cannot read properties of undefined (reading 'children')
Cannot resolve a Slate point from DOM point: [object Text],1
…
Cannot resolve a Slate point from DOM point: [object Text],5
Cannot read properties of null (reading 'anchor')
```

We're using Slate.

Here's the configuration of our text field :
(both rich text fields in activity don't work)

```
import type { Field } from "payload/types";

export const activity: Field[] = [
  {
    name: "link",
    label: { en: "Link > Activity", fr: "Lien > Activité" },
    type: "text",
    localized: true,
  },
  {
    name: "title",
    label: { en: "Title > Activity", fr: "Titre > Activité" },
    type: "text",
    localized: true,
  },
  {
    name: "image",
    label: { en: "Image > Activity", fr: "Image > Activité" },
    type: "upload",
    relationTo: "media",
    localized: true,
  },
  {
    name: "description",
    label: { en: "Description > Activity", fr: "Description > Activité" },
    type: "richText",
    localized: true,
  },
  {
    name: "details",
    label: { en: "Details > Activity", fr: "Détails > Activité" },
    type: "richText",
    localized: true,
  },
];

import type { Field } from "payload/types";
import { activity } from "./activity";

export const mustDoActivities: Field = {
  name: "mustdo",
  label: false,
  type: "group",
  fields: [
    {
      name: "title",
      label: {
        en: "Title > Must do activities",
        fr: "Titre > Activités incontournables",
      },
      type: "text",
      localized: true,
    },
    {
      name: "paragraph",
      label: {
        en: "Paragraph > Must do activities",
        fr: "Paragraph > Activités incontournables",
      },
      type: "richText",
      localized: true,
    },
    {
      name: "list",
      label: {
        en: "Must do activities list",
        fr: "Liste des activités incontournables",
      },
      type: "array",
      fields: activity,
    },
  ],
};
```

The issue manifests itself in a few activities, but not all of them. Some work, some don't.

Thank you in advance for your help and dedication!

### To Reproduce

I didn't identify a clear reproduction path as of yet.

### Payload Version

2.24

### Adapters and Plugins

db-postgres

**Comment by ClementCardonnel** [comment]
Update: it looks like the issue was of our own making!

We developed a CSV importer to add content in bulk to payload, and we believe we've made a mistake there. We imported content to the rich text fields in a bad format.

Here's an example of the incorrect data that was added and which generated the issues previously described in this ticket:

```
[{ text: row.activity10Details }]
```

And here's an example of the data as it should have been formatted in order for the fields to work properly:

```
[{ children: [{ text: row.activity10Details }] }]
```

Formatting our content in a correct manner fixed the issues with the rich text fields.

I hope this ticket will be of use for the community down the line. I'll mark it as resolved.

The only feedback I would like to provide to the payload team is the following:
1. I don't know how much longer Slate is to be supported, but improving the error messages, or clearly showing an error message for improperly formatted data would go a long way for us to solve this kind of issues.
2. We had difficulties in creating our own custom CSV importer, in part because of a lack of details in the documentation about the rich text format. Improving the documentation to clarify how rich text should be formatted would help as well. If this is just standard rich text and it's something that is documented (I don't know much about rich text myself), providing a link to third party documentation would hopefully do the trick.

**Comment by paulpopus** [comment]
Thanks for the update @ClementCardonnel , glad you fixed it!

Regarding RichText, slate will continue to be maintained (usable) but all of our efforts have and will be going into Lexical since it handles all of these things a lot more gracefully.
