### ISSUE TITLE
[Payload 1.0.4] payload.authenticate is undefined.

### ISSUE THREAD

**Issue by wojciechkrol** [payloadcms/payload#769]
# Bug Report

After 1.0.4 upgrade `payload.authenticate` middle no longer work.

## Current Behavior

Can't start Payload due to `throw new TypeError('app.use() requires a middleware function')` error. `payload.authenticate` seems to be `undefined`.

## Steps to Reproduce
1. Add `app.use(payload.authenticate)` to your `server.ts` file

## Detailed Description

Payload 1.0.4

**Comment by DanRibbens** [comment]
Go ahead and reopen the issue if it isn't answered completely.

**Comment by wojciechkrol** [comment]
Hello @DanRibbens ,

Unfortunately, I have another problem connected with `payload.authentication`. It looks like this issue started on version `0.19.0` and continues today. Here is an example:

server.ts
```
...
app.use(payload.authenticate);

app.get('/api/invoices/:id/test', async function (req, res) {
  const invoice = await payload.findByID<Invoice>({
    collection: "invoices",
    id: req.params.id,
  });
  
  res.json(invoice);
});

app.get('*', function (req, res) {
  res.status(404).json(...);
});
```

When I use this middleware and call custom endpoint it executes but get an error: `Error: Cannot set headers after they are sent to the client` and shows my custom 404 response. It looks like this endpoint and fallback route runs simultaneously. When I disable `payload.authentication` middleware (just comment this line) custom routes work well as expected.

**Comment by jmikrut** [comment]
Hey @wojciechkrol — I just tried recreating this with a Payload method within an endpoint, like you suggested, and still can't reproduce ☠️ 

Is it possible that you can send us your repo so I can do some debugging? Alternatively, a thought I have is that this may be caused by the fact that you're binding your custom route to `/api/test` - and if you're using the default Payload `/api` route, there might be a conflict there somewhere. Not sure about specifics, but I could imagine a scenario where Express is mounting _**two**_ copies of `payload.authenticate` somehow in your app. But, I can get very similar code to yours to run on `1.0.7` no problem:

```
import express from 'express';
import payload from 'payload';
import path from 'path';

require('dotenv').config({
  path: path.resolve(__dirname, '../.env'),
});

const app = express();

payload.init({
  secret: process.env.PAYLOAD_SECRET_KEY,
  mongoURL: process.env.MONGO_URL,
  express: app,
});

app.use(payload.authenticate);

app.get('/api/pages/:id/test', async ({ payload }, res) => {
	const results = await payload.find({
		collection: 'pages',
	})

	return res.json(results);
})

app.get('*', function (req, res) {
  res.status(404).json({ message: 'Not found'});
})

app.listen(3000);

```

If you want to try and mount your custom route within your `invoices` collection, [we now support a way to do that right within Payload](https://payloadcms.com/docs/rest-api/overview#custom-endpoints), so you wouldn't even need to use the `payload.authenticate` anymore.  Maybe try that?

**Comment by wojciechkrol** [comment]
> Not sure about specifics, but I could imagine a scenario where Express is mounting two copies of payload.authenticate somehow in your app.

Well, you were right. It looks like using `app.use(payload.authenticate)` causes this issue, and somehow it is already mounted in the application (not directly by me) - so every express route already knows about `user`.

I apologize for the confusion. I haven't known about this change.

**Comment by jmikrut** [comment]
No worries!!

Yep - that is mounted for all of our Payload routes, and is just exposed for re-use if you need it completely outside of Payload’s scoped routers. But I don't think there have been any changes internally here, so it's strange that `0.19.0` would be the start of your issue. We _**did**_ release the majority of the work necessary for our Extensible Authentication Strategies within `0.19.0`, so I am sure there's something in there that has changed (order, etc) but I can't identify it off-hand.

Anyway, thank you for bringing this up. Seriously. Good to have on our radar and happy we could get it sorted!
