### ISSUE TITLE
Virtual field is actually created in the database (Postgresql)

### ISSUE THREAD

**Issue by bmamouri** [payloadcms/payload#7864]
### Payload Version

3.0.0-beta.91

### Node Version

18.20.4

### Next.js Version

15.0.0-canary.104

### Describe the Bug

The virtual field or calculated field that I add to my collection is actually created in the database. Base on [this blog post](https://payloadcms.com/blog/learn-how-virtual-fields-can-help-solve-common-cms-challenges) and the [field hooks](https://payloadcms.com/docs/beta/hooks/fields) document, the virtual field shoule be removed before saving. I have added the `beforeChange` hook. But it is actually created in the database with null value.

This is my collection definition.

```js
import { CollectionConfig } from 'payload'

const getFullname = async ({ data }: any) => {
  return data.code + ' ' + data.name
}

export const Category: CollectionConfig = {
  slug: 'category',
  admin: {
    group: 'Products',
    useAsTitle: 'fullName',
  },
  fields: [
    {
      name: 'code',
      type: 'text',
      required: true,
    },
    {
      name: 'name',
      type: 'text',
      required: false,
    },
    {
      name: 'fullName',
      type: 'text',
      admin: {
        readOnly: true,
      },
      hooks: {
        beforeChange: [
          ({ siblingData }) => {
            delete siblingData['fullName']
          },
        ],
        afterRead: [getFullname],
      },
    },
  ],
}
```

### Reproduction Steps

As mentioned above

**Comment by DanRibbens** [comment]
Thanks for reporting @bmamouri!

I see why you opened a bug for this but I'm going consider this to be a new feature and close the issue. 

For MongoDB this isn't an issue because keys aren't made until data is assigned, however as you pointed out for any SQL based DBs you will see columns being created. In the field config there isn't a current way to tell the database adapter to ignore the field.

We're evaluating this PR that is related https://github.com/payloadcms/payload/pull/7621 and would handle this feature so you can follow along there.
