### ISSUE TITLE
No source map file generate when debug server code

### ISSUE THREAD

**Issue by smoothdvd** [payloadcms/payload#8015]
### Environment Info

```text
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.97
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
```

### Describe the Bug

I want to debug the payload 3.0 project in vscode, using the launch file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Next.js: debug server-side",
            "type": "node-terminal",
            "request": "launch",
            "cwd": "${workspaceFolder}/apps/api",
            "sourceMaps": true,
            "command": "pnpm run dev"
        },
    ]
}   
```

But there is no source map files generated, so the breakpoint is not be intercepted.

### Reproduction Steps

Run with debug in vscode and set a breakpoint at the code in my-route.ts
 
<img width="330" alt="Screenshot 2024-09-01 at 2 43 11 PM" src="https://github.com/user-attachments/assets/0b3d6dfa-8793-45a2-8952-abef8548f822">
<img width="749" alt="Screenshot 2024-09-01 at 2 42 49 PM" src="https://github.com/user-attachments/assets/867861ff-5af3-4431-8ce6-9a1d312a4546">

**Comment by javierlinked** [comment]
I have been trying for a couple of days with no success on debugging, except for the bare minimum of setting an endpoint in 'tsx' files.

Ideally would be having the 'attach to' possibility since we are preparing migration to version 3, and all our logic is on endpoints/hooks. We are just a service/graphql endpoint.

An example on how to set up debugger would be highly appreciated. I already checked Nextjs docs and https://github.com/payloadcms/payload-3.0-demo this repo. But something is missing in my case.

**Comment by smoothdvd** [comment]
remove NODE_OPTIONS=--no-deprecation to make the VSCode debugger bind breakpoints correctly
