### ISSUE TITLE
Payload says in dev mod when run with NODE_ENV=production node server.js

### ISSUE THREAD

**Issue by smoothdvd** [payloadcms/payload#8055]
### Environment Info

```text
Binaries:
  Node: 20.17.0
  npm: 10.8.2
  Yarn: N/A
  pnpm: 9.9.0
Relevant Packages:
  payload: 3.0.0-beta.98
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:21 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8103
  Available memory (MB): 8192
  Available CPU cores: 8
```

### Describe the Bug

Payload says in dev mod but NODE_ENV=production

### Reproduction Steps

* build payload app in standalone mode
* run with command NODE_ENV=production node .next/standalone/server.js
* visit any payload pages
* log says:
```
It looks like you've run Payload in dev mode, meaning you've dynamically pushed changes to your database.

If you'd like to run migrations, data loss will occur. Would you like to proceed?
```

### Adapters and Plugins

postgresAdapter

**Comment by r1tsuu** [comment]
This is not depended on whether you run your app with `NODE_ENV=development` or `NODE_ENV=production`.
You most likely copied the development database to the prod. In development, we use database push instead of migrations and the thing is that we can't mix them. This is described in the docs https://payloadcms.com/docs/beta/database/postgres#prototyping-in-development-mode

You can remove all the rows from the `payload_migrations` with `batch= -1` like this:
```sql
DELETE FROM payload_migrations WHERE batch=-1
```
Then the warning should go out.
