### ISSUE TITLE
Upgrade `file-type`

### ISSUE THREAD

**Issue by benmccann** [payloadcms/payload#8111]
### Link to reproduction

https://github.com/payloadcms/payload/blob/08fdbcacc02c1768770516c2dd2e22df7bc48843/packages/payload/package.json#L97

### Environment Info

```text
beta.100
```

### Describe the Bug

payload 3 currently uses file-type 17 while the latest is file-type 19. The newer version is smaller and would remove a couple of transitive dependencies

### Reproduction Steps

See https://github.com/payloadcms/payload/blob/08fdbcacc02c1768770516c2dd2e22df7bc48843/packages/payload/package.json#L97

**Comment by AlessioGr** [comment]
I'll upgrade this to file-type 19.3.0. Cannot upgrade to the latest (file-type 19.4.0 and higher) because of the following:

- they added 3 new dependencies through https://github.com/sindresorhus/file-type/pull/649 (total: 9). 19.3.0 seems to have the least amount of dependencies (total: 6). 17.1.6 had 11.
- they decided to go full combat mode against typescript. https://github.com/sindresorhus/file-type/commit/5034fc1f7025554b1df81ed6cb1d3b32ce239eb2 broke file-type when used in combination with `moduleResolution: Bundler` or jest (jests esm support sucks, it's probably falling into the same trap). They're trying to get typescript to fix it and keep the package broken for these configurations until that happens: https://github.com/sindresorhus/file-type/issues/652. I respect that, but I'd also like to stay as far away from this as possible until it's resolved

**Comment by benmccann** [comment]
that's awesome!! thank you!

> Damn I wish there was a way to add comments to package.json's to document these decisions

there is, but it's really hacky...

```
"comment": "we use version 19.3 of file-type because..."
```

**Comment by AlessioGr** [comment]
Fixed by https://github.com/payloadcms/payload/pull/8195

> there is, but it's really hacky...
> 
> "comment": "we use version 19.3 of file-type because..."

Yeea that might be a bit too hacky - I'm hoping for jsonc support or something like that to be added in the future!
