### ISSUE TITLE
Cannot read properties of undefined (reading 'id') after deleting image

### ISSUE THREAD

**Issue by PP-Tom** [payloadcms/payload#8133]
### Environment Info

```text
Payload: beta.100
Node: v20.11.0
Next: 15.0.0-canary.104
```

### Describe the Bug

TypeError: Cannot read properties of undefined (reading 'id') after deleting image

### Reproduction Steps

1. Create a upload collection (Collection A)
2. Create a collection (Collection B) that has an `upload` field related to the upload "Collection A"
3. Create an item in "Collection B" and upload an image
4. In the upload collection (Collection A) delete the uploaded image
5. Try to open up the previous item in "Collection B"

**Comment by PP-Tom** [comment]
@paulpopus MongoDB, sorry :-)

**Comment by paulpopus** [comment]
So this is expected behaviour with Mongo, since it doesn't remove any references on its own unlike Postgres which can handle deletion of references at a database level.

Our recommendation here is to use an afterDelete hook to use the Local API and update any documents where the media was deleted to remove its ID from the field.

The error is caused by the ID simply not existing anymore and if you inspect the database you'll see that it's still referenced.
