### ISSUE TITLE
Text field unique=true not working in mongodb database

### ISSUE THREAD

**Issue by qasimali09** [payloadcms/payload#8504]
### Environment Info

```text
Payload: 3.0 beta
Database: Mongodb
Nextjs: 15.0.0-canary.160
```

### Describe the Bug

Payload beta text field unique not working in mongodb

### Reproduction Steps

Payload beta text field unique not working in mongodb

**Comment by r1tsuu** [comment]
Hey @qasimali09, please see this issue https://github.com/payloadcms/payload/issues/7274 and Dan's answer, it does seem like your case.

**Comment by DanRibbens** [comment]
Something to note about indexes in mongodb is that once an index is created on a field, it won't change after that so adding `unique: true` on your field won't impact the index. I imagine if you're landing on this thread and wondering why it the issue was closed this may explain the situation.

To remedy this, drop the existing index for the field and start Payload again, it will create a `unique` index and you should be all set.

If you have a large DB and are concerned with dropping an index in production, you can instead create a new db migration and make the index in a migration using the mongoose model call [syncIndexes()](https://mongoosejs.com/docs/api/model.html#Model.()) with `payload.collections[myCollectionSlug].Model.syncIndexes()`.
