### ISSUE TITLE
Admin bar not showing in qa env

### ISSUE THREAD

**Issue by KBambharoliya** [payloadcms/payload#8538]
### Describe the Bug

I have implemented payload-adminbar and it's working fine in my local. but when i deploy changes in qa environment earlier it gives CROS error after adding below changes it's gone but users data  getting null for "api/users/me" if i'm login in qa cms .
How to resolve this issue.

customHeaders:- pattern: "**/*"
headers:
- key: Access-Control-Allow-Headers
value: "*"
- key: Access-Control-Allow-Methods
value: GET, HEAD, POST, PUT, DELETE
- key: Access-Control-Allow-Origin
value: "url of -qa (frontend)"
- key: Access-Control-Allow-Credentials
value: "true"

### To Reproduce

I have implemented payload-adminbar and it's working fine in my local. but when i deploy changes in qa environment earlier it gives CROS error after adding below changes it's gone but users data  getting null for "api/users/me" if i'm login in qa cms .
How to resolve this issue.

customHeaders:- pattern: "**/*"
headers:
- key: Access-Control-Allow-Headers
value: "*"
- key: Access-Control-Allow-Methods
value: GET, HEAD, POST, PUT, DELETE
- key: Access-Control-Allow-Origin
value: "url of -qa (frontend)"
- key: Access-Control-Allow-Credentials
value: "true"

### Payload Version

2.13.0

**Comment by paulpopus** [comment]
Hey, when deploying you need to setup CORS and CSRF to point to your deployed server's domain.

Docs: https://payloadcms.com/docs/production/preventing-abuse#cross-origin-resource-sharing-cors

Here is how it's setup in our website template for v2: https://github.com/payloadcms/payload/blob/main/templates/website/src/payload/payload.config.ts#L77

So for github my config would be like
```ts
cors: ['https://github.com'],
csrf: ['https://github.com'],
```

Without `/` at the end. And ideally behind some kind of logic check and an env variable so that you can have it disabled locally and configurable per environment.
