### ISSUE TITLE
Mimetypes in upload not working correctly.

### ISSUE THREAD

**Issue by AlphaMoonbaseBerlin** [payloadcms/payload#8673]
### Environment Info

Windows 10
Payload Beta v3
Node 20.4

### Describe the Bug

Adding values to the mimeTypes field of an uplaodCollection does not have the described effect, instead still allowing to select all files.

### Reproduction Steps

Create a new collection and add the following config:
```
...
upload : {
        filesRequiredOnCreate : true,
        mimeTypes : ["application/pdf"]
    },
...
```
It allows the selection of any arbitrary file and only throws an error when trying to upload.

Expected Behaviour: It is not possible to allow selecting a file with the wrong extension/mimetype.

Wished Behaviour: 
- Being able to directly define the file-extension. Arbitrary filetypes that are not part fo the defined MIME-Types are not defineable.
- Allowing for access-control and hooks on the upload field to at least manually create the wished behaviour.

**Comment by akhrarovsaid** [comment]
Hey @AlphaMoonbaseBerlin,

I have a [PR up for this](https://github.com/payloadcms/payload/pull/8710) issue. Now, whether or not it will be merged is another question entirely. There are some nuances when it comes to restricting files by mimetypes on the client. It's not obvious to me the expected behavior of, say for example, the `bulkUpload` or `drag-and-drop` functionality with respect to mimetypes. I've chosen to simply omit the files, but maybe the Payload team has a better idea.
