### ISSUE TITLE
Clicking text field border moves cursor to the start

### ISSUE THREAD

**Issue by AlessioGr** [payloadcms/payload#8853]
https://github.com/user-attachments/assets/b436eca6-e204-406c-b42a-08a1ae07e89c

Click in middle of text field => cursor is at the end of the text.

Click close to the border of text field => cursor is at the start of the text. Expected: cursor is at the end of the text

**Comment by paulpopus** [comment]
I don't think this is a problem as this is default browser behaviour.

_In chrome_ when clicking on the field label, it puts the cursor to the end of the text.
_In firefox_ it puts selects the entire text in the input.

Clicking on the top border, will place the cursor to the beginning of the input for both browsers.  
Clicking on the bottom border will place the cursor to the end of the input instead.


My guess is that this happens due to document flow and we shouldn't mess with default behaviour here.
For what it's worth I tested different sizing methods between changing height to auto and removing padding and the behaviour remains consistent so I'll close this issue as won't fix
