### ISSUE TITLE
Mismatching "lexical" dependency versions found: lexical@0.20.0

### ISSUE THREAD

**Issue by gor3a** [payloadcms/payload#9134]
### Describe the Bug

I used `npx create-payload-app@beta` after the setup and dev the app I got it
```
Error: Mismatching "lexical" dependency versions found: lexical@0.20.0 (Please change this to 0.18.0). All "lexical" packages must have the same version. This is an error with your set-up, not a bug in Payload. Please go to your package.json and ensure all "lexical" packages have the same version.
```

### Link to the code that reproduces this issue

npx create-payload-app@beta -t website

### Reproduction Steps

1. Run `npx create-payload-app@beta` 
2. Append the project name 
3. Append the supabase pq connection string 
4. Run project
5. Get the error

### Which area(s) are affected? (Select all that apply)

plugin: richtext-lexical, plugin: richtext-slate

### Environment Info

```text
Payload:3.0.0-beta.128
```

**Comment by OkanUnalll** [comment]
I have same problem.

also when I create a project with the latest beta version, some places in the project have incorrect imports. Example:

![Image](https://github.com/user-attachments/assets/70f3093a-c7ac-4155-965f-e8b9b3e10845)

Something seems to be missing in the called npm packages.

**Comment by khnn** [comment]
I had an issue that might be related as well. The LinkFeature stopped working and I ended up adding lexical@0.18 as a dependency to my package.json. After deleting the lock file and reinstalling the packages, it worked again.

**Comment by akhrarovsaid** [comment]
Hey @gor3a, @khnn, and @OkanUnalll,

I believe this was fixed as of `beta.128` by [this PR](https://github.com/payloadcms/payload/pull/9141).

**Comment by AlessioGr** [comment]
Closing, as this is now fixed in beta.128/129. We've also upgraded lexical to 0.20.0.

As I often see people struggling to get the correct dependencies installed, I'll include this little guide here ⬇

---

Here's the easiest and most reliable way to manage your packages, so that you have no dependency issues:

1. upgrade all payload packages to beta.129 (or whatever the latest v3 payload version is). Be sure to, for all payload packages, specify `"3.0.0-beta-129"` in your package.json versions and not just `"beta"`.
2. if manually installed, upgrade all lexical dependencies to `"0.20.0"`
3. remove all caret (`^`) symbols from your package.json. I have frequently seen incorrect versions being installed due to the caret.
4. remove `node_modules` (and `pnpm-lock.yaml` if you still have issues)
5. run `pnpm install`
6. restart your IDE or TypeScript server

`pnpm` is the most reliable package manager. `npm` is less stable than `pnpm` and slower. `yarn` v1 is unsupported. Modern yarn may be fine, though I have no personal experience with it.

If you're coming from beta 127 or earlier, please follow this migration guide: https://github.com/payloadcms/payload/releases/tag/v3.0.0-beta.128
