### ISSUE TITLE
[Payload 3.0] Missing custom actions in the custom pages

### ISSUE THREAD

**Issue by dinhmai74** [payloadcms/payload#9338]
### Describe the Bug

The actions views are missing in the custom pages after upgrade to payload 3 latest from beta-126.

Here the clip demo the bug:
https://github.com/user-attachments/assets/ab5e8537-d576-445e-9114-5ca50b42795b

### Link to the code that reproduces this issue

https://github.com/dinhmai74/payload-missing-actions

### Reproduction Steps

- go to admin page -> we can see the actions view there

1. go to the custom page (/admin/custom-views) -> nothing show in the actions position

### Which area(s) are affected? (Select all that apply)

area: ui

### Environment Info

```text
Binaries:
  Node: 22.8.0
  npm: 10.8.2
  Yarn: 1.22.21
  pnpm: 9.4.0
Relevant Packages:
  payload: 3.0.0
  next: 15.0.0
  @payloadcms/db-postgres: 3.0.0
  @payloadcms/email-nodemailer: 3.0.0
  @payloadcms/graphql: 3.0.0
  @payloadcms/next/utilities: 3.0.0
  @payloadcms/payload-cloud: 3.0.0
  @payloadcms/richtext-lexical: 3.0.0
  @payloadcms/translations: 3.0.0
  @payloadcms/ui/shared: 3.0.0
  react: 19.0.0-rc-65a56d0e-20241020
  react-dom: 19.0.0-rc-65a56d0e-20241020
Operating System:
  Platform: linux
  Arch: x64
  Version: #1 SMP Thu Oct 5 21:02:42 UTC 2023
  Available memory (MB): 31974
  Available CPU cores: 32
```

**Comment by kendelljoseph** [comment]
Hi @dinhmai74 ,

The repo you linked does not have an actions folder in the `src/` can you include it?
https://github.com/dinhmai74/payload-missing-actions/blob/f6714777b72f20d764c7b41c5c6690e721cb4072/src/payload.config.ts#L20C12-L20C13

**Comment by dinhmai74** [comment]
@kendelljoseph , what do you mean by that? https://github.com/dinhmai74/payload-missing-actions/blob/main/src/actions.tsx is my actions file. Are there new ways to implement it? As you can see in the demo, it appears on the normal pages but disappears in the custom pages when using the DefaultTemplate componen

**Comment by akhrarovsaid** [comment]
Hey @dinhmai74,

I think what's happening here is intentional. In Payload admin views, `viewActions` are provided to the default template by Payload as you would expect - you author them, like you have, and they show up appropriately. However, when you're creating a custom view the responsibility of passing those view actions are yours as Payload is not driving the default view for you. This sounds intentional and expected to me.

You can pass your custom view actions to the default template via the `viewActions` prop passed directly to the `DefaultTemplate` component. [See here](https://github.com/payloadcms/payload/blob/main/packages/next/src/templates/Default/index.tsx#L23) and have a look just below where I linked you to see them used. Hopefully this works for you.

**Comment by JarrodMFlesch** [comment]
@dinhmai74 I think what @akhrarovsaid said is correct, you _could_ recreate these yourself but you would incur some overhead by re-running a function we already run. I have opened #9404 which will allow your custom component to receive viewActions as a prop that you will then need to pass to your `DefaultTemplate` component.

**Comment by kendelljoseph** [comment]
> [@kendelljoseph](https://github.com/kendelljoseph) , what do you mean by that? https://github.com/dinhmai74/payload-missing-actions/blob/main/src/actions.tsx is my actions file. Are there new ways to implement it? As you can see in the demo, it appears on the normal pages but disappears in the custom pages when using the DefaultTemplate componen

My mistake - the file was there!
